Repository magento/adobe-stock-integration, pull requests merged in 2019-08, with the labels that each got.

#278 [MFTF]: User filters safe content images
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminUserApplySafeSearchFilterActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockFilterSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersSafeContentImagesTest.xml
Labels: Progress: approved

#279 [MFTF]: User chooses the number of images to display on the page
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminDataGridSelectCustomPerPageActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserCanSelectNumberOfImagesToDisplayTest.xml
Labels: Progress: approved

#273 [MFTF]: User navigates to next previous image from the currently viewed
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserNavigatesBetweenImagesOnThePreviewTest.xml
Labels: Progress: approved

#250 [MFTF] Adding the MFTF test that check the Adobe Stock Images filters' availability
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertIsVisibleAdobeStockFilterElementActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserHasAccessToGridFiltersTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#280 magento/adobe-stock-integration#71: Preserve the image grid state inc…
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Progress: approved

#254 Adjust WebApi tests for AdobeStockAsset module
  AdobeStockAsset/Model/Asset.php
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/ResourceModel/UserProfile.php
  AdobeStockAsset/Model/ResourceModel/UserProfile/Collection.php
  AdobeStockAsset/Test/Api/AssetRepository/DeleteTest.php
  AdobeStockAsset/Test/Api/AssetRepository/GetByIdTest.php
  AdobeStockAsset/Test/Api/AssetRepository/SaveTest.php
  AdobeStockAssetApi/Api/AssetRepositoryInterface.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockClient/Model/Client.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
Labels: Partner: Atwix, Progress: approved, partners-contribution

#281 fixed correct Test Conection button validation result
  AdobeStockAsset/view/adminhtml/web/js/validate-api-key.js
Labels: Progress: approved

#296 FIX: undefined field name in the recursive document to asset convert
  AdobeStockAsset/Model/DocumentToAsset.php
Labels: Backend, bug

#294 [MFTF]: Test Stability
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminUserClearSearchFiltersActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersImagesByColor.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersImagesByOrientationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersImagesByPriceTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersImagesByTypeTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersSafeContentImagesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserSearchesStockImagesByKeywords.xml
Labels: Progress: approved

#292 Code cleanup
  AdobeStockAsset/Model/ResourceModel/Category.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockClient/Model/SearchParametersProvider/ContentType.php
  AdobeStockClient/Model/SearchParametersProvider/Isolated.php
  AdobeStockClient/Model/SearchParametersProvider/MediaId.php
  AdobeStockClient/Model/SearchParametersProvider/Offensive.php
  AdobeStockClient/Model/SearchParametersProvider/Orientation.php
  AdobeStockClient/Model/SearchParametersProvider/Pagination.php
  AdobeStockClient/Model/SearchParametersProvider/Sorting.php
  AdobeStockClient/Model/SearchParametersProvider/Words.php
  AdobeStockImage/Model/SaveImagePreview.php
  AdobeStockImageApi/Api/SaveImagePreviewInterface.php
Labels: Partner: Space 48, Progress: approved, partners-contribution

#300 Cleanup
  AdobeStockClient/Model/SearchParametersProvider/Sorting.php
Labels: Partner: Space 48, Progress: changes requested, partners-contribution

#301 #218 [MFTF] cleanup
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersIsolatedImageOnlyTest.xml
Labels: Partner: Space 48, partners-contribution

#302 Destination path utilization and selecting uploaded image in media gallery
  AdobeStockImage/Controller/Adminhtml/Preview/Download.php
  AdobeStockImage/Model/Storage.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Progress: approved

#261 #259 : Add comment with Redirect URL and Redirect URL pattern next to Client Secret field in Stores Configuration
  AdobeStockAsset/Model/System/Config/Comment.php
  AdobeStockAsset/etc/adminhtml/system.xml
Labels: Progress: changes requested

#304 277: save asset keywords + provide keywords repository
  AdobeStockAsset/Model/AssetKeywordRepository.php
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/ResourceModel/Keyword.php
  AdobeStockAsset/etc/db_schema.xml
  AdobeStockAsset/etc/db_schema_whitelist.json
  AdobeStockAsset/etc/di.xml
  AdobeStockAssetApi/Api/AssetKeywordRepositoryInterface.php
  AdobeStockAssetApi/Api/Data/KeywordInterface.php
Labels: Backend, Progress: changes requested

#338 #337 : Update SDK dependency to 1.1.0
  AdobeStockAsset/Controller/Adminhtml/OAuth/Callback.php
  AdobeStockAsset/composer.json
  AdobeStockClient/composer.json
Labels: Progress: approved

#336 326: add permanent error message on invalid API key
  AdobeStockAsset/Model/Block/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/view/adminhtml/templates/system/config/connection.phtml
  AdobeStockAsset/view/adminhtml/templates/system/config/testconnection.phtml
  AdobeStockAsset/view/adminhtml/web/js/connection.js
  AdobeStockAsset/view/adminhtml/web/js/validate-api-key.js
  AdobeStockAsset/view/adminhtml/web/template/connection.html
Labels: Backend, Frontend/UI

#333 Refactor and clean up the comment model
  AdobeStockAsset/Model/System/Config/Comment.php
Labels: Backend, Progress: approved

#327 Fixed issue with state save on image preview
  AdobeStockImageAdminUi/view/adminhtml/templates/panel.phtml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/masonry.js
  AdobeStockImageAdminUi/view/adminhtml/web/panel.js
Labels: Progress: changes requested

#342 Cleanup and code standards adjustments
  AdobeStockAsset/Controller/Adminhtml/OAuth/Callback.php
  AdobeStockAsset/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/AssetKeywordRepository.php
  AdobeStockAsset/Model/Block/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/ResourceModel/Keyword.php
Labels: Backend, Progress: changes requested

#334 Move masonry grid to AdobeUi module
  AdobeStockImageAdminUi/composer.json
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeUi/LICENSE.txt
  AdobeUi/LICENSE_AFL.txt
  AdobeUi/README.md
  AdobeUi/composer.json
  AdobeUi/etc/module.xml
  AdobeUi/modman
  AdobeUi/registration.php
  AdobeUi/view/adminhtml/web/css/source/_module.less
  AdobeUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeUi/view/adminhtml/web/js/components/grid/column/image.js
  AdobeUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
  AdobeUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeUi/view/adminhtml/web/template/grid/column/image.html
  AdobeUi/view/adminhtml/web/template/grid/column/overlay.html
  AdobeUi/view/adminhtml/web/template/grid/masonry.html
  modman
Labels: Progress: review

#370 Refactored redirect URI retrieving logic
  AdobeStockAdminUi/Model/System/Config/Comment.php
Labels: Partner: Atwix, Progress: approved, partners-contribution

#365 Cover with unit tests DocumentToAsset class an UserProfileRepository
  AdobeIms/Test/Unit/Controller/Adminhtml/OAuth/CallbackTest.php
  AdobeIms/Test/Unit/Model/GetTokenTest.php
  AdobeIms/Test/Unit/Model/UserProfileRepositoryTest.php
  AdobeStockAsset/Test/Unit/DocumentToAssetTest.php
Labels: Progress: review, unit tests coverage request

#335 #298 : Introduce GetAssetList API service
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockAsset/Test/Unit/Model/GetAssetListTest.php
  AdobeStockAsset/etc/di.xml
  AdobeStockAsset/etc/webapi.xml
  AdobeStockAssetApi/Api/GetAssetListInterface.php
  AdobeStockImage/Model/GetImageList.php
Labels: Progress: changes requested

#379 Add Adobe UI module to the composer.json
  _metapackage/composer.json
Labels: Progress: approved

#325 #285 Remove unnecessary conversions of asset when loading it from API
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockAsset/Test/Unit/Model/GetAssetListTest.php
  AdobeStockAssetApi/Api/GetAssetListInterface.php
  AdobeStockImage/Model/GetImageList.php
  AdobeStockImage/Model/SaveImagePreview.php
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
  AdobeStockImageAdminUi/Test/Unit/Model/Listing/DataProviderTest.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeStockImageApi/Api/GetImageListInterface.php
  AdobeUi/view/adminhtml/web/js/components/grid/column/image.js
Labels: Partner: Space 48, Progress: review, partners-contribution

#375 MFTF Minor cleanup
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserAccessesAdobeStockPanelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserFiltersImagesByColorTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserSearchesStockImagesByKeywordsTest.xml
Labels: Partner: Space 48, Progress: approved, partners-contribution

#354 330: Remove unused fields from DB schema
  AdobeStockAsset/Test/Api/AssetRepository/SaveTest.php
  AdobeStockAsset/etc/db_schema.xml
  AdobeStockAsset/etc/db_schema_whitelist.json
  AdobeStockAssetApi/Api/Data/CategoryInterface.php
  AdobeStockAssetApi/Api/Data/CreatorInterface.php
Labels: Asset Component, Backend, Progress: changes requested

#383 FIX: refactor the getImageByAdobeId and execute SaveImagePreview class methods
  AdobeStockImage/Model/SaveImagePreview.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Backend

#367 Redirect URI pattern with escaped hostname
  AdobeStockAdminUi/Model/System/Config/Comment.php
Labels: Partner: Atwix, Progress: review, partners-contribution

#363 "Disable" state for "Search Adobe Stock" to prevent error in console
  AdobeStockImageAdminUi/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButton.php
  AdobeStockImageAdminUi/Test/Unit/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButtonTest.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
Labels: Progress: review

#385 373: image related image series - base implementation
  AdobeStockClient/Model/SearchParametersProvider/Pagination.php
  AdobeStockClient/Model/SearchParametersProvider/SimpleFilters.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/SimpleFiltersTest.php
  AdobeStockClient/etc/di.xml
  AdobeStockImage/Model/GetImageSeries.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/Series.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/model/messages.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeUi/view/adminhtml/web/css/source/_module.less
  AdobeUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Backend, Frontend/UI, Progress: changes requested

#388 Cover Download Controller with unit test
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/Download.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/DownloadTest.php
Labels: Progress: approved, unit tests coverage request

#358 #331: Close image preview when filters are changed
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Progress: approved

#394 Fixed token length in the database
  AdobeIms/etc/db_schema.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#263 [MFTF] User controls access to Adobe Stock images from Admin Panel in ACL Automation
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminNavigateToCreatedUserRoleActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminUserHaveNoAccessToAdobeStockActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserControlsAccessToAdobeStockImagesFromAdminPanelInACLTest.xml
Labels: MFTF coverage, Progress: review

#264 [MFTF]: User sees stock image attributes localized automation
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserSeesStockImageAttributesLocalizedTest.xml
Labels: MFTF coverage, Progress: review

#377 [MFTF] User Sees keywords in the image preview Automation + Hide button
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertNumberOfKeywordsInImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserSeesKeywordsInTheImagePreviewTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: MFTF coverage, Progress: review

#361 [MFTF] User sees images attributes in the image preview
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertVisibleImagePreviewAttributesActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserSeesImagesAttributesInTheImagePreviewTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: MFTF coverage, Progress: review

#269 [MFTF]: User saves image preview
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockSavePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAssertAdobeStockImageSavedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminUserSavesImagePreviewTest.xml
Labels: MFTF coverage, Progress: review

#384 #374: Click on the keyword initiates new search
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Progress: changes requested

#386 Display image licensing confirmation popup
  AdobeIms/etc/db_schema.xml
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Test/Integration/Model/ClientTest.php
  AdobeStockClientApi/Api/ClientInterface.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetQuota.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/etc/acl.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Partner: Atwix, Progress: review, partners-contribution

#343 Provide meaningful naming for saved image files
  AdobeStockImage/Model/Storage.php
  AdobeStockImage/Test/Unit/Model/StorageTest.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Progress: changes requested
