Repository magento/adobe-stock-integration, pull requests merged in 2019-10, with the labels that each got.

#406 #359: added Locate button for saved preview images
  AdobeStockAsset/Model/AppendAttributes.php
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Asset/LoadByIds.php
  AdobeStockAsset/etc/di.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Partner: Atwix, Progress: changes requested, cdmageconf2019, partners-contribution

#503 #issue-502 Fixed the issue with not loaded "More from this series" and "More from this model" sections when the preview was switched via next or previous buttons
  AdobeUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Partner: Atwix, Progress: approved, partners-contribution

#492 Move default premium filter to di.xml configuration
  AdobeStockClient/Model/SearchParametersProvider/Premium.php
  AdobeStockClient/etc/di.xml
  AdobeStockImage/etc/di.xml
Labels: Progress: changes requested, cdmageconf2019

#438 427 : [Refactoring] Extract Logout service model from Logout controller
  AdobeIms/Controller/Adminhtml/User/Logout.php
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/Model/Config.php
  AdobeIms/Model/LogOut.php
  AdobeIms/Test/Unit/Controller/Adminhtml/User/LogoutTest.php
  AdobeIms/Test/Unit/Model/LogOutTest.php
  AdobeIms/etc/di.xml
  AdobeImsApi/Api/Data/ConfigInterface.php
  AdobeImsApi/Api/LogOutInterface.php
Labels: Progress: approved

#496 Show alternative license popup view on zero credit
  AdobeStockClient/Model/Client.php
  AdobeStockClientApi/Api/ClientInterface.php
  AdobeStockImageAdminUi/Block/Adminhtml/Panel.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetQuota.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/GetQuotaTest.php
  AdobeStockImageAdminUi/view/adminhtml/templates/panel.phtml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/panel.js
Labels: Partner: Atwix, Progress: changes requested, cdmageconf2019, partners-contribution

#417 Fixed error when "Search Adobe Stock" button is clicked before the grid is rendered
  AdobeStockImageAdminUi/view/adminhtml/web/panel.js
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
Labels: Progress: changes requested

#455 [MFTF]: User returns to the same state of image grid after saving image preview
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockExpandImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAssertAdobeStockThumbnailsNumberActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewAttributesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagesPreviewNavigationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockListingStateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavePreviewTest.xml
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
Labels: MFTF coverage, Progress: approved

#459 User quota is not updated during authorization
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/view/adminhtml/web/js/action/authorization.js
  AdobeIms/view/adminhtml/web/js/config.js
  AdobeStockAdminUi/view/adminhtml/templates/signIn.phtml
  AdobeStockAdminUi/view/adminhtml/web/js/signIn.js
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/UserQuota.php
  AdobeStockClientApi/Api/ClientInterface.php
  AdobeStockClientApi/Api/Data/UserQuotaInterface.php
  AdobeStockImageAdminUi/Block/Adminhtml/Panel.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetQuota.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/GetQuotaTest.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Progress: changes requested

#499 Add user picture to the profile popup
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/Model/Config.php
  AdobeIms/Model/GetImage.php
  AdobeIms/Model/UserProfile.php
  AdobeIms/Test/Unit/Controller/Adminhtml/OAuth/CallbackTest.php
  AdobeIms/etc/config.xml
  AdobeIms/etc/db_schema.xml
  AdobeIms/etc/db_schema_whitelist.json
  AdobeIms/etc/di.xml
  AdobeIms/view/adminhtml/web/js/user.js
  AdobeImsApi/Api/Data/ConfigInterface.php
  AdobeImsApi/Api/Data/UserProfileInterface.php
  AdobeImsApi/Api/GetImageInterface.php
  AdobeStockAdminUi/Block/Adminhtml/SignIn.php
  AdobeStockAdminUi/view/adminhtml/templates/signIn.phtml
  AdobeStockAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockAdminUi/view/adminhtml/web/js/signIn.js
  AdobeStockAdminUi/view/adminhtml/web/template/signIn.html
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
Labels: Progress: review, cdmageconf2019

#504 #issue-399 Added the ability to switch the image preview according to a selected image from "More from this series" and "More from this model"
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/RelatedImagesTest.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Atwix, Progress: approved, partners-contribution

#475 Update Adobe Stock ReadMe files
  AdobeIms/README.md
  AdobeImsApi/README.md
  AdobeStockAdminUi/README.md
  AdobeStockAsset/README.md
  AdobeStockAsset/composer.json
  AdobeStockAssetApi/README.md
  AdobeStockClient/README.md
  AdobeStockClientApi/README.md
  AdobeStockImage/README.md
  AdobeStockImageAdminUi/README.md
  AdobeStockImageApi/README.md
  AdobeUi/README.md
Labels: Partner: Space 48, partners-contribution

#517 Add image name field to license confirmation popup && Image preview is saved event if operation is cancelled
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/modal/adobe-modal-prompt-content.html
Labels: Progress: changes requested

#473 Fix: Error when loading grid after logout on adobe side
  AdobeIms/Model/FlushUserTokens.php
  AdobeIms/Model/GetAccessToken.php
  AdobeIms/Model/LogOut.php
  AdobeIms/etc/di.xml
  AdobeImsApi/Api/FlushUserTokensInterface.php
  AdobeImsApi/Api/GetAccessTokenInterface.php
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/Connection.php
  AdobeStockClient/Model/ConnectionFactory.php
  AdobeStockClient/Test/Integration/Model/ClientTest.php
  AdobeStockClientApi/Api/ClientInterface.php
  AdobeStockImageAdminUi/Model/SignInConfigProvider.php
Labels: Progress: approved

#524 Unit test coverage request
  AdobeIms/Model/GetImage.php
  AdobeIms/Test/Unit/Controller/Adminhtml/User/ProfileTest.php
  AdobeIms/Test/Unit/Model/FlushUserTokensTest.php
  AdobeIms/Test/Unit/Model/GetAccessTokenTest.php
  AdobeIms/Test/Unit/Model/GetImageTest.php
  AdobeIms/Test/Unit/Model/GetTokenTest.php
  AdobeIms/Test/Unit/Model/UserAuthorizedTest.php
Labels: unit tests coverage request

#532 Covering the License controller by Unit Tests
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/LicenseTest.php
Labels: Partner: Atwix, Progress: approved, partners-contribution

#537 Covering the SignInConfigProvider by Unit Test
  AdobeIms/Test/Unit/Model/UserAuthorizedTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/SignInConfigProviderTest.php
Labels: Partner: Atwix, partners-contribution

#535 #520 : Image preview is not closed when applying sorting to the grid
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
Labels: Progress: approved

#536 #448 : [MFTF] User sees images from the same series as the currently viewed image
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertNumberOfImagesUnderMoreForThisSeriesActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesTest.xml
Labels: Progress: approved

#544 Unit test coverage request
  AdobeStockClient/Model/ConnectionWrapper.php
  AdobeStockClient/Test/Unit/Model/ClientTest.php
  AdobeStockClient/Test/Unit/Model/ConnectionWrapperTest.php
Labels: Progress: approved, unit tests coverage request

#533 Position of user profile block is dependent on browser window size
  AdobeIms/view/adminhtml/web/css/source/_module.less
Labels: Progress: changes requested

#547 fixing eslint warnings in JS files
  AdobeIms/view/adminhtml/web/js/action/authorization.js
  AdobeIms/view/adminhtml/web/js/signIn.js
  AdobeStockAdminUi/view/adminhtml/web/js/connection.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/keywords.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/model/messages.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
  AdobeUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Progress: changes requested

#550 Initialised .gitignore file
  .gitignore
Labels: Progress: approved

#522 License asset that was saved as preview
  AdobeStockAsset/Model/AppendAttributes.php
  AdobeStockAsset/Model/Asset.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Asset/LoadByIds.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/Storage.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/StorageTest.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/actions.html
Labels: Partner: Atwix, Progress: approved, partners-contribution

#538 #489 Cover \Magento\AdobeStockImage\Model\GetImageList with a unit test
  AdobeStockImage/Test/Unit/Model/GetImageListTest.php
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#556 Adding a bottom toolbar to the images grid
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Atwix, partners-contribution

#549 Cover \Magento\AdobeStockImageAdminUi\Ui\Component\Listing\Filter\Color with a unit test
  AdobeStockImageAdminUi/Test/Unit/Ui/Component/Listing/Filter/ColorTest.php
Labels: Progress: changes requested, unit tests coverage request

#562 Added Test to cover Magento\AdobeStockClient\Model\SearchParametersProvider\MediaId
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/MediaIdTest.php
Labels: Progress: approved, mleu2019

#563 Fixed blank page issue After adobe stock integration installation
  AdobeStockAdminUi/Block/Adminhtml/System/Config/TestConnection.php
Labels: Community Insider: Cedcommerce, Progress: approved, community-insider-contribution

#568 [Unit test coverage] SignIn block
  AdobeIms/Test/Unit/Block/Adminhtml/SignInTest.php
Labels: Partner: Atwix, Progress: approved, partners-contribution, unit tests coverage request

#570 #issue-351 Update styles of image preview
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Atwix, partners-contribution

#552 #424 : Add licensed images label to licensed images thumbnail in the grid
  AdobeStockClient/composer.json
  AdobeStockClient/etc/di.xml
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/LicensedOverlay.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeUi/view/adminhtml/web/css/source/_module.less
  AdobeUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeUi/view/adminhtml/web/template/grid/column/overlay.html
Labels: Progress: changes requested

#574 FIX: keywords save during the image save
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
Labels: Backend, Community Insider: Magecom, Progress: approved, community-insider-contribution

#577 [Unit test coverage] Covering the Premium filter
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/PremiumTest.php
Labels: Partner: Atwix, partners-contribution, unit tests coverage request

#569 added similar filter code. #557
  AdobeStockClient/Model/SearchParametersProvider/Similar.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/SimilarTest.php
  AdobeStockClient/etc/di.xml
Labels: Progress: changes requested

#592 Add unit test for 'get asset keywords' command
  AdobeMediaGallery/Test/Unit/Model/Keyword/Command/GetAssetKeywordsTest.php
Labels: Progress: changes requested, mm19es

#595 #553 - Hide ImageName Field
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Progress: changes requested

#580 See more link is visible even if there are less than 4 related images
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
Labels: Progress: changes requested

#599 [Unit test coverage] Covering the SaveAssetLinks by Unit Test
  AdobeMediaGallery/Test/Unit/Model/Keyword/Command/SaveAssetLinksTest.php
Labels: Partner: Atwix, partners-contribution

#543 #450 : [MFTF] User searches for images from the same series as the currently viewed one
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockApplySameSeriesFilterActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdobeStockFilterIsNotAppliedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockFilterSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSeeMoreSeriesFilterTest.xml
Labels: Award: MFTF test coverage, MFTF coverage, Progress: review

#545 [MFTF] Admin user Sign in and Sign out from adobe stock automation
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockAssertUserLoggedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockAssertUserNotLoggedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockClickSignInActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImsPopupClickSignInActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImsPopupSignInFillUserDataActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockUserSignOutActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockConfigData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInSignOutTest.xml
  dev/tests/acceptance/.env
Labels: MFTF coverage, Progress: review

#605 Enhance AdobeImsApi sources
  AdobeImsApi/Api/Data/UserProfileInterface.php
  AdobeImsApi/Api/GetImageInterface.php
  AdobeImsApi/Api/UserProfileRepositoryInterface.php
Labels: Progress: approved

#612 Fixed bug when the extra margin was applied to the reopened image preview
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/keywords.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/keywords.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
  AdobeUi/view/adminhtml/web/css/source/_module.less
  AdobeUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
Labels: Progress: review
