Repository magento/adobe-stock-integration, pull requests merged in 2019-12, with the labels that each got.

#819 Added MFTF test for viewing licensed label
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLicensedImageViewLabelTest.xml
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#786 Licensed image is not saved into the folder where preview of same image was saved
  AdobeStockImage/Model/SaveLicensedImage.php
  AdobeStockImage/Test/Unit/Model/SaveLicensedImageTest.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/License.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/SaveLicensed.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageApi/Api/SaveLicensedImageInterface.php
Labels: Progress: changes requested

#813 [WIP] Directory tree
  MediaGalleryUi/Model/Filesystem/ImagesProvider.php
  MediaGalleryUi/Ui/Component/Listing/Columns/DirectoryTree.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Progress: approved

#835 Shifting view controls to the left by applying a right padding
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: review

#844 #issue-832 Added pagination to media gallery grid and adjusted the images provider for allowing paging
  MediaGalleryUi/Model/Filesystem/ImagesProvider.php
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Partner: Atwix, partners-contribution

#817 #774 : MediaGalleryUiApi module added
  MediaGalleryUi/Model/Config.php
  MediaGalleryUi/composer.json
  MediaGalleryUi/etc/di.xml
  MediaGalleryUiApi/Api/ConfigInterface.php
  MediaGalleryUiApi/LICENSE.txt
  MediaGalleryUiApi/LICENSE_AFL.txt
  MediaGalleryUiApi/README.md
  MediaGalleryUiApi/composer.json
  MediaGalleryUiApi/etc/module.xml
  MediaGalleryUiApi/modman
  MediaGalleryUiApi/registration.php
  _metapackage/composer.json
  modman
Labels: Progress: changes requested

#823 Improve the callback action error handling
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
Labels: Backend, Community Insider: Magecom, community-insider-contribution, enhancement

#812 UNIT TEST COVERAGE: cover the service command with unit tests
  AdobeStockClient/Model/Client/Files.php
  AdobeStockClient/Test/Unit/Model/Client/Files/CurlRequestFailed.php
  AdobeStockClient/Test/Unit/Model/Client/Files/CurlResultContainsEmptyFilesTest.php
  AdobeStockClient/Test/Unit/Model/Client/Files/CurlResultSuccessFilesExistsTest.php
  AdobeStockClient/Test/Unit/Model/Client/Files/EmptyIdsTest.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetList.php
Labels: Backend, Community Insider: Magecom, Progress: changes requested, community-insider-contribution, enhancement, unit tests coverage

#818 Proof of concept for hiding tabs with related images
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
Labels: Partner: Atwix, Progress: review, partners-contribution

#853 #827 : Element '#adobe-stock-tabs-content .three-dots' can be overlapped by "Similar keywords"
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved

#849 REFACTORING: adjustments for the code and tests for the MediaGalleryUI module
  MediaGalleryUi/Model/Filesystem/ImagesProvider.php
  MediaGalleryUi/Model/Listing/DataProvider.php
  MediaGalleryUi/Test/Unit/Model/ConfigTest.php
  MediaGalleryUi/Test/Unit/Model/Filesystem/ImagesProviderTest.php
Labels: Backend, Community Insider: Magecom, Progress: approved, community-insider-contribution, enhancement

#857 Grid header has extra space in right side
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/actions.html
Labels: Progress: approved

#859 Not enough permissions error message is not shown to Admin user on attempt to license image
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Progress: review

#869 Refactored MFTF schema paths
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-configuration.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-filters.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-grid.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-ims.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-keywords.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-license.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-preview.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-see-more.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration.xml
Labels: Partner: Zilker Technology, partners-contribution

#870 850 fix see more btn on preview
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
Labels: Progress: approved, cddublin2019

#877 Fix PHPStan errors: return exception instead of throwing it in "handleException" method
  AdobeStockClient/Model/ConnectionWrapper.php
Labels: Partner: Monsoon, partners-contribution

#858 Added MFTF test for Adobe sign in failure when Secret Key is incorrect
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIncorrectSecretSignInTest.xml
Labels: Award: MFTF test coverage, Award: category of expertise, MFTF coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#868 Added MFTF test for Adobe Stock panel bookmarks functionality
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockSaveViewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridBookmarksTest.xml
Labels: Award: MFTF test coverage, Award: category of expertise, MFTF coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#842 [WIP] #834 : Add upload date filter to media gallery grid
  MediaGalleryUi/Model/Filesystem/ImagesProvider.php
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Award: category of expertise, Progress: changes requested

#843 [WIP] #833 : Add Modification date filter to media gallery grid
  MediaGalleryUi/Model/AssetIndexer.php
  MediaGalleryUi/Model/ResourceModel/Grid/Asset/Collection.php
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Award: category of expertise, Progress: approved

#875 #862 : "Found 2 elements with non-unique id" warning in browser console on Adobe Stock grid
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Award: bug fix, Award: category of expertise, Progress: approved
