Repository magento/adobe-stock-integration, pull requests merged in 2019-09, with the labels that each got.

#413 Unit test For Creator,category repository
  AdobeStockAsset/Test/Unit/Model/CategoryRepositoryTest.php
  AdobeStockAsset/Test/Unit/Model/CreatorRepositoryTest.php
  AdobeStockAsset/Test/Unit/Model/DocumentToAssetTest.php
Labels: unit tests coverage request

#410 Cover SaveImagePreview with unit test
  AdobeStockImage/Test/Unit/Model/SaveImagePreviewTest.php
Labels: unit tests coverage request

#409 Cover GetQuota Controller with unit test
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetQuota.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/GetQuotaTest.php
Labels: unit tests coverage request

#396 Unit test for series controller
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/SeriesTest.php
Labels: Progress: review, unit tests coverage request

#412 Unit test For GetImageSeries model
  AdobeStockImage/Test/Unit/Model/GetImageSeriesTest.php
Labels: Progress: review, unit tests coverage request

#418 Added loading animation for license popup
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Partner: Atwix, Progress: review, partners-contribution

#404 Fixed the issue with broken overlay functionality
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Atwix, Progress: approved, partners-contribution

#405 Added an ability to specify image name during saving preview
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Partner: Atwix, Progress: approved, partners-contribution

#357 Add Sing-in link to the images grid
  AdobeIms/Block/Adminhtml/SignIn.php
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/Model/GetToken.php
  AdobeIms/Model/UserAuthorized.php
  AdobeIms/Model/UserProfile.php
  AdobeIms/etc/config.xml
  AdobeIms/etc/db_schema.xml
  AdobeIms/etc/db_schema_whitelist.json
  AdobeIms/etc/di.xml
  AdobeIms/view/adminhtml/web/js/action/authorization.js
  AdobeIms/view/adminhtml/web/js/action/signIn.js
  AdobeIms/view/adminhtml/web/js/config.js
  AdobeIms/view/adminhtml/web/js/user.js
  AdobeImsApi/Api/Data/UserProfileInterface.php
  AdobeImsApi/Api/UserAuthorizedInterface.php
  AdobeStockAdminUi/Block/Adminhtml/ImsConfig.php
  AdobeStockAdminUi/Block/Adminhtml/User.php
  AdobeStockAdminUi/view/adminhtml/templates/signIn.phtml
  AdobeStockAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockAdminUi/view/adminhtml/web/template/signIn.html
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/view/adminhtml/layout/cms_wysiwyg_images_index.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Backend, Frontend/UI, Progress: review

#303 Move default filter value from ContentType to GetImageList service
  AdobeStockClient/Model/SearchParametersProvider/ContentType.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/ContentTypeTest.php
  AdobeStockImage/Model/GetImageList.php
  AdobeStockImage/etc/di.xml
Labels: Backend, Progress: review

#416 [MFTF] User searches images by clicking on keywords in image preview
  AdobeStockAdminUi/Test/Mftf/Test/AdminAdobeStockConfigTest.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminImagePreviewKeywordSearchActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockFilterSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockColorFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIsolatedFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPageNumberTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockTypeFilterTest.xml
Labels: MFTF coverage, Progress: approved

#423 Update save Preview mftf test
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAssertAdobeStockImageSavedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavePreviewTest.xml
Labels: MFTF coverage, Progress: approved

#408 #397 : "More from this model" image preview section
  AdobeStockAdminUi/view/adminhtml/web/js/config.js
  AdobeStockClient/etc/di.xml
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Test/Unit/Model/GetRelatedSeriesTest.php
  AdobeStockImage/etc/di.xml
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/RelatedImages.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/RelatedImagesTest.php
  AdobeStockImageAdminUi/view/adminhtml/templates/panel.phtml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/panel.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeUi/view/adminhtml/web/js/components/grid/column/image.js
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
Labels: Progress: changes requested

#407 #398: "See more" link applies Series filter to the grid
  AdobeStockImageAdminUi/Ui/Component/Listing/Filter/SerieId.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Progress: approved

#392 #322 Track code coverage of unit test in scope of travis build
  .coveralls.yml
  .travis.yml
  README.md
  dev/tests/unit/phpunit.xml
  dev/travis/before_install.sh
  dev/travis/before_script.sh
Labels: Partner: Space 48, Progress: review, partners-contribution

#476 #463 : [Styles] "See more" link for Series and Model related images styles
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Progress: approved

#477 #462 : "See more" link applies Model filter to the grid
  AdobeStockImageAdminUi/Ui/Component/Listing/Filter/RelatedImages.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Progress: approved

#479 ASI-472 Use JsonHexTag instead of native json_encode
  AdobeStockAdminUi/Block/Adminhtml/SignIn.php
  AdobeStockAdminUi/view/adminhtml/templates/signIn.phtml
Labels: Progress: approved

#481 #467 : [Styles] Keywords appearance in the image preview
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Progress: approved

#494 Use hydrator instead of getData method in Save Resource models
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Category/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/Save.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
Labels: Progress: approved, cdmageconf2019

#501 449 mtft user sees images under this model tab
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertNumberOfImagesUnderMoreForThisModelActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewImagesWithTheSameModelTest.xml
Labels: Progress: approved, cdmageconf2019

#493 ASI-488: [Unit tests] Cover \Magento\AdobeStockClient\Model\StockFile…
  AdobeStockClient/Model/StockFileToDocument.php
  AdobeStockClient/Test/Unit/Model/StockFileToDocumentTest.php
Labels: Community Insider: Magecom, Progress: changes requested, cdmageconf2019, community-insider-contribution

#498 484: fixed related images proportionally in the image preview
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved, cdmageconf2019

#468 #317 Ensure dependencies between modules is correct
  AdobeIms/composer.json
  AdobeImsApi/composer.json
  AdobeStockAdminUi/Block/Adminhtml/SignIn.php
  AdobeStockAdminUi/composer.json
  AdobeStockAsset/Model/GetAssetById.php
  AdobeStockAsset/Model/SaveAsset.php
  AdobeStockAsset/composer.json
  AdobeStockAsset/etc/di.xml
  AdobeStockAssetApi/Api/GetAssetByIdInterface.php
  AdobeStockAssetApi/Api/SaveAssetInterface.php
  AdobeStockAssetApi/composer.json
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/SearchParameterProviderInterface.php
  AdobeStockClient/Model/SearchParametersProvider/ContentType.php
  AdobeStockClient/Model/SearchParametersProvider/Isolated.php
  AdobeStockClient/Model/SearchParametersProvider/MediaId.php
  AdobeStockClient/Model/SearchParametersProvider/Offensive.php
  AdobeStockClient/Model/SearchParametersProvider/Orientation.php
  AdobeStockClient/Model/SearchParametersProvider/Pagination.php
  AdobeStockClient/Model/SearchParametersProvider/Premium.php
  AdobeStockClient/Model/SearchParametersProvider/SimpleFilters.php
  AdobeStockClient/Model/SearchParametersProvider/Sorting.php
  AdobeStockClient/Model/SearchParametersProvider/Words.php
  AdobeStockClient/Model/SearchParametersProviderComposite.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProviderCompositeTest.php
  AdobeStockClient/composer.json
  AdobeStockClientApi/composer.json
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SaveImagePreview.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImage/Test/Unit/Model/SaveImagePreviewTest.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/composer.json
  AdobeStockImage/etc/di.xml
  AdobeStockImageAdminUi/Controller/Adminhtml/License/License.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/Download.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/RelatedImages.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/DownloadTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/RelatedImagesTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButtonTest.php
  AdobeStockImageAdminUi/composer.json
  AdobeStockImageApi/Api/GetRelatedImagesInterface.php
  AdobeStockImageApi/Api/SaveImageInterface.php
  AdobeStockImageApi/composer.json
  AdobeUi/composer.json
Labels: Partner: Space 48, Progress: changes requested, partners-contribution
