Repository magento/adobe-stock-integration, pull requests merged in 2019-05, with the labels that each got.

#46 Add documentation in classes, in the form of comments.
  AdobeStockAsset/Model/Client.php
  AdobeStockImage/Model/Image.php
  AdobeStockImageAdminUi/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButton.php
Labels: comments

#49 Add setup script (#10)
  AdobeStockImage/etc/db_schema.xml
Labels: Partner: Imagination Media, partners-contribution

#50 #11 Implement setup script for user metadata
  AdobeStockAsset/etc/db_schema.xml
  AdobeStockAsset/etc/db_schema_whitelist.json
Labels: Partner: Space 48, partners-contribution

#61 #11 Add additional foreign key constraints
  AdobeStockAsset/etc/db_schema.xml
  AdobeStockAsset/etc/db_schema_whitelist.json
Labels: Partner: Space 48, partners-contribution

#62 #11 remove db_schema from AdobeStockImage
  AdobeStockAsset/etc/db_schema.xml
  AdobeStockImage/etc/db_schema.xml
Labels: Partner: Space 48, partners-contribution
