Repository magento/adobe-stock-integration, pull requests merged in 2019-06, with the labels that each got.

#52 #29 User configures Adobe Stock integration
  AdobeStockAsset/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/Block/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/Client.php
  AdobeStockAsset/etc/acl.xml
  AdobeStockAsset/etc/adminhtml/routes.xml
  AdobeStockAsset/etc/adminhtml/system.xml
  AdobeStockAsset/etc/config.xml
  AdobeStockAsset/view/adminhtml/templates/system/config/testconnection.phtml
  AdobeStockAssetApi/Api/ClientInterface.php
  AdobeStockImage/etc/acl.xml
  AdobeStockImageApi/Api/GetImageListInterface.php
Labels: Award: category of expertise, Partner: Space 48, partners-contribution

#51 Implement models and the plugin to cleanup stock metadata after image…
  AdobeStockAsset/Model/Asset.php
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/Keyword.php
  AdobeStockAsset/Model/ResourceModel/Asset.php
  AdobeStockAsset/Model/ResourceModel/Asset/Collection.php
  AdobeStockAsset/Model/ResourceModel/Keyword.php
  AdobeStockAsset/etc/di.xml
  AdobeStockAssetApi/Api/AssetRepositoryInterface.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockAssetApi/Api/Data/AssetSearchResultsInterface.php
  AdobeStockAssetApi/Api/Data/CategoryInterface.php
  AdobeStockAssetApi/Api/Data/CreatorInterface.php
  AdobeStockAssetApi/Api/Data/KeywordInterface.php
  AdobeStockImage/Plugin/Product/Gallery/Processor.php
  AdobeStockImage/etc/di.xml
Labels: Partner: Imagination Media, partners-contribution

#77 #29 Update reference to block in phtml
  AdobeStockAsset/view/adminhtml/templates/system/config/testconnection.phtml
Labels: Partner: Space 48, partners-contribution

#80 Add missing strict type declaration
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/PremiumPrice/Options.php
Labels: Partner: Space 48, partners-contribution

#79 #16 Add search filter for the isolated attribute
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Isolated/Options.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Partner: Space 48, partners-contribution

#81 15 safe content search filter
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Offensive/Options.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Partner: Space 48, partners-contribution

#98 #90 Add explanation message to the configuration
  AdobeStockAsset/etc/adminhtml/system.xml
Labels: Partner: Space 48, partners-contribution

#109 Fix small typo :)
  AdobeStockImageAdminUi/view/adminhtml/web/template/masonry.html
Labels: Partner: Space 48, mmuk2019, partners-contribution

#107 #88 Display error message when Adobe Stock API credentials are missing
  AdobeStockAsset/Model/Client.php
Labels: Partner: Space 48, partners-contribution

#110 magento/adobe-stock-integration#102: implemented urlencode for filters
  AdobeStockImage/Model/GetImageList.php
Labels: mmuk2019

#108 #85 fix for getApiKey() must be of the type string, null returned
  AdobeStockAsset/Model/Client.php
  AdobeStockAsset/Model/Config.php
  AdobeStockAssetApi/Api/Data/ConfigInterface.php
Labels: Partner: Space 48, mmuk2019, partners-contribution

#121 Updated modman imports
  AdobeStockClientApi/modman
  modman
Labels: kharkiv2019

#119 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Partner: Space 48, partners-contribution

#120 Add Contributing Guidelines
  .github/CONTRIBUTING.md
Labels: Partner: Space 48, partners-contribution

#122 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: Partner: Space 48, partners-contribution

#99 #18 Implement search filter for the color attribute
  AdobeStockClient/Model/SearchParametersProvider/Colors.php
  AdobeStockClient/etc/di.xml
  AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Color.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/filter/color.html
Labels: Partner: Space 48, partners-contribution

#137 magento/adobe-stock-integration:#93 - Specify correct ACL resources …
  AdobeStockAsset/etc/adminhtml/system.xml
  AdobeStockImageAdminUi/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButton.php
  AdobeStockImageAdminUi/etc/acl.xml
  AdobeStockImageAdminUi/view/adminhtml/layout/cms_wysiwyg_images_index.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Partner: ISM eCompany, Progress: changes requested, partners-contribution

#133 FEATURE: add connection adapter and separate connection initialization from client object
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/ConnectionFactory.php
Labels: Backend, Progress: changes requested, enhancement

#136 #14 : Implement content type search filter
  AdobeStockClient/Model/SearchParametersProvider/ContentType.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ContentType/Options.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Progress: changes requested

#123 FEATURE: add exception manager for adobe stock integration client
  AdobeStockClient/Model/Client.php
  AdobeStockClientApi/Api/ClientInterface.php
  AdobeStockImage/Model/GetImageList.php
Labels: Backend, Progress: changes requested, enhancement, kharkiv2019
