Repository magento/adobe-stock-integration, pull requests merged in 2019-07, with the labels that each got.

#147 FIX: minor adjustments according to the Magento 2 standards
  AdobeStockAsset/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/Block/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/ResourceModel/Keyword.php
  AdobeStockAsset/Model/SearchResults.php
  AdobeStockClient/Model/SearchParametersProvider/ContentType.php
  AdobeStockClient/Model/SearchParametersProvider/Isolated.php
  AdobeStockClient/Model/SearchParametersProvider/Offensive.php
  AdobeStockClient/Model/SearchParametersProvider/Orientation.php
  AdobeStockClient/Model/SearchParametersProvider/Pagination.php
  AdobeStockClient/Model/SearchParametersProviderComposite.php
  AdobeStockImage/Plugin/Product/Gallery/Processor.php
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
Labels: Backend, Cleanup, Progress: approved

#134 20: added sorting to images listing
  AdobeStockClient/Model/SearchParametersProvider/Sorting.php
  AdobeStockClient/etc/di.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/listing.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/toolbar.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/sorting.html
Labels: Progress: approved, kharkiv2019

#150 #149 Move conf back to system section
  AdobeStockAsset/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/etc/acl.xml
  AdobeStockAsset/etc/adminhtml/system.xml
Labels: Partner: Space 48, Progress: approved, partners-contribution

#152 #143 : Implement checkbox grid filter (Yes/No select replacement)
  AdobeStockClient/Model/SearchParametersProvider/Isolated.php
  AdobeStockClient/Model/SearchParametersProvider/Offensive.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Checkbox.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/filter/checkbox.html
Labels: Progress: review

#155 Cleanup
  AdobeStockAsset/Model/Asset.php
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/Config.php
  AdobeStockAsset/Model/ResourceModel/Asset.php
  AdobeStockAsset/Model/ResourceModel/Asset/Collection.php
  AdobeStockAsset/Model/ResourceModel/Keyword.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/Config.php
  AdobeStockClient/Model/ConnectionFactory.php
  AdobeStockClient/Model/SearchParametersProvider/Isolated.php
  AdobeStockClient/Model/SearchParametersProvider/SimpleFilters.php
  AdobeStockClient/Model/SearchParametersProvider/Sorting.php
  AdobeStockClientApi/Api/ClientInterface.php
  AdobeStockClientApi/Api/SearchParameterProviderInterface.php
  AdobeStockImage/Model/GetImageList.php
  AdobeStockImage/Test/Unit/Model/GetImageListTestTest.php
  AdobeStockImageAdminUi/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButton.php
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
  AdobeStockImageAdminUi/Test/Unit/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButtonTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/Listing/DataProviderTest.php
  AdobeStockImageAdminUi/Test/Unit/Ui/Component/Listing/Filter/ImageTest.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ContentType/Options.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Image.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Isolated/Options.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Offensive/Options.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Orientation/Options.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/PremiumPrice/Options.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Filter/Color.php
  AdobeStockImageAdminUi/view/adminhtml/templates/panel.phtml
  AdobeStockImageApi/Api/GetImageListInterface.php
Labels: Partner: Space 48, Progress: approved, partners-contribution

#158 Fix phpdoc and add return types to AssetInterface
  AdobeStockAsset/Model/Asset.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
Labels: Progress: approved

#159 Fix phpdoc and add return types to AssetRepositoryInterface and KeywordInterface
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/Keyword.php
  AdobeStockAssetApi/Api/AssetRepositoryInterface.php
  AdobeStockAssetApi/Api/Data/KeywordInterface.php
Labels: Progress: approved

#161 Fixed incorrect behavior with Safe search filter
  AdobeStockClient/Model/SearchParametersProvider/Offensive.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Progress: approved

#160 [MFTF] User accesses Adobe Stock images via Magento admin
  AdobeStockImageAdminUi/Test/Mftf/LICENSE.txt
  AdobeStockImageAdminUi/Test/Mftf/LICENSE_AFL.txt
  AdobeStockImageAdminUi/Test/Mftf/README.md
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserAccessesAdobeStockPanelTest.xml
Labels: Progress: approved

#168 Refactored masonry grid component
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/image.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/masonry.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/listing.html
Labels: Progress: approved

#169 #164 : WebAPI for image search
  AdobeStockImage/etc/webapi.xml
Labels: Progress: approved

#140 #89: Implement overlay UI component for Masonry grid image
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Image.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/masonry.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/overlay.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/masonry.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/masonry.html
Labels: Progress: review

#146 issue 86: Filters were not reset to its original state but message "Something went wrong with processing current custom view and filters have been reset to its original state. Please edit filters then click apply." appeared
  AdobeStockClient/Model/SearchParametersProvider/Words.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/WordsTest.php
  AdobeStockClient/etc/di.xml
Labels: Progress: review

#172 ASI-166: Writing unit tests for module AdobeStockAsset
  AdobeStockAsset/Test/Unit/Controller/Adminhtml/System/Config/TestConnectionTest.php
Labels: Progress: approved

#171 [WIP]: magento/adobe-stock-integration#8: Expand preview image on thumbnail …
  AdobeStockAsset/Model/Asset.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockClient/Model/Client.php
  AdobeStockClient/etc/di.xml
  AdobeStockImage/Model/GetImageList.php
  AdobeStockImage/Test/Unit/Model/GetImageListTestTest.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image.html
Labels: Progress: review

#228 ASI-128: Client error: Api Key is invalid if User is allowed to click on by client and is not allowed by server
  AdobeStockClient/Model/Client.php
  AdobeStockImage/Model/GetImageList.php
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
Labels: Progress: review

#227 ASI-103: stock.adobe.io returns 500 for some requests even when they looks like valid
  AdobeStockClient/Model/Client.php
Labels: Progress: review

#233 #232 : Color filter UI is broken
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved

#229 Fix the issue with Expected Magento\Framework\Model\AbstractModel, got Asset and adjusting code style
  AdobeStockAsset/Model/Asset.php
Labels: Partner: Atwix, Progress: approved, partners-contribution

#167 13 login via adobe stock oauth: backend
  AdobeStockAsset/Controller/Adminhtml/OAuth/Callback.php
  AdobeStockAsset/Model/Config.php
  AdobeStockAsset/Model/ResourceModel/UserProfile.php
  AdobeStockAsset/Model/ResourceModel/UserProfile/Collection.php
  AdobeStockAsset/Model/UserProfile.php
  AdobeStockAsset/Model/UserProfileRepository.php
  AdobeStockAsset/etc/adminhtml/system.xml
  AdobeStockAsset/etc/di.xml
  AdobeStockAssetApi/Api/Data/UserProfileInterface.php
  AdobeStockAssetApi/Api/UserProfileRepositoryInterface.php
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/Config.php
  AdobeStockClient/Model/OAuth/TokenResponse.php
  AdobeStockClient/etc/config.xml
  AdobeStockClientApi/Api/ClientInterface.php
Labels: Award: complex, Community Insider: Magecom, Progress: approved, community-insider-contribution

#235 HOTFIX: remove second time imported search criteria interface
  AdobeStockClient/Model/Client.php
Labels: bug

#126 FEATURE: improve test button notification presentation
  AdobeStockAsset/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/Block/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/etc/adminhtml/system.xml
  AdobeStockAsset/view/adminhtml/templates/system/config/testconnection.phtml
  AdobeStockAsset/view/adminhtml/web/js/validate-api-key.js
  AdobeStockClient/Model/Client.php
  AdobeStockClientApi/Api/ClientInterface.php
Labels: Backend, Progress: changes requested, enhancement

#238 117: redirect admin user to the login page when the session is expired
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/masonry.js
Labels: Award: bug fix, Progress: approved, bug

#165 ASI-163: Writing integration test for module AdobeStockClient for client
  AdobeStockClient/Test/Integration/Model/ClientTest.php
Labels: Progress: review

#236 #231 : Add a tooltip to Isolated Assets filter
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/filter/checkbox.html
Labels: Progress: changes requested

#241 Fix the issue with not specified namespace in API methods docs
  AdobeStockAssetApi/Api/AssetRepositoryInterface.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockImageApi/Api/GetImageListInterface.php
Labels: Partner: Atwix, Progress: approved, bug, partners-contribution

#240 Fixed the issue with saving asset model
  AdobeStockAsset/Model/Asset.php
Labels: Partner: Atwix, Progress: approved, bug, partners-contribution

#246 #244 Removed scope label for Test Connection button
  AdobeStockAsset/Model/Block/Adminhtml/System/Config/TestConnection.php
Labels: Partner: Atwix, partners-contribution

#222 #170 : WebAPI test: Image search
  AdobeStockImage/Test/Api/SearchExecuteTest.php
Labels: Progress: review

#242 Added WebAPI test for AssetRepository::getById
  AdobeStockAsset/Test/Api/AssetRepository/GetByIdTest.php
  AdobeStockAsset/Test/_files/asset.php
  AdobeStockAsset/etc/acl.xml
  AdobeStockAsset/etc/webapi.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#225 #173 #174 #177 Add Webapi for Asset repository
  AdobeStockAsset/Test/Api/AssetRepository/DeleteTest.php
  AdobeStockAsset/Test/Api/AssetRepository/SaveTest.php
  AdobeStockAsset/etc/acl.xml
  AdobeStockAsset/etc/webapi.xml
  AdobeStockImage/etc/acl.xml
  AdobeStockImage/etc/webapi.xml
Labels: Partner: Space 48, Progress: approved, partners-contribution

#226 #95 save image preview to the Magento media gallery
  AdobeStockImage/Model/Storage.php
  AdobeStockImage/Test/Unit/Model/StorageTest.php
  AdobeStockImage/etc/di.xml
Labels: Partner: Space 48, Progress: approved, partners-contribution

#249 Refactor: clean up the product image delete plugin and small fix for listing xml
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/Config.php
  AdobeStockAssetApi/Api/Data/AssetSearchResultsInterface.php
  AdobeStockImage/Plugin/Product/Gallery/Processor.php
  AdobeStockImage/Test/Unit/Plugin/Product/Gallery/ProcessorTest.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Backend, Cleanup, Progress: changes requested, enhancement

#252 #175 : WebAPI for AssetRepository::getList
  AdobeStockAsset/Test/Api/AssetRepository/AssetListTest.php
  AdobeStockAsset/etc/webapi.xml
Labels: Award: test coverage

#255 GetImageListTest cleanup
  AdobeStockImage/Test/Unit/Model/GetImageListTest.php
Labels: Partner: Space 48, partners-contribution

#247 234 provide ability to login via adobe stock oauth frontend
  AdobeStockAsset/Controller/Adminhtml/OAuth/Callback.php
  AdobeStockAsset/Model/UserProfile.php
  AdobeStockAsset/etc/db_schema.xml
  AdobeStockAssetApi/Api/Data/UserProfileInterface.php
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/Config.php
  AdobeStockClient/etc/config.xml
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/authorization.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/model/messages.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
Labels: Award: complex, Community Insider: Magecom, Progress: review, community-insider-contribution

#239 #207 [MFTF]: UserAccessesAdobeStockPanelTest refactoring and full cover of test case from the ticket
  AdobeStockAsset/etc/di.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockCloseSearchModalActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockOpenNextPageActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockOpenSearchModalActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockSetConfigActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAssertAdobeStockCurrentPageNumberActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAssertAdobeStockThumbnailsNumberActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockConfigData.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockModalData.xml
  AdobeStockImageAdminUi/Test/Mftf/README.md
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserAccessesAdobeStockPanelTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/panel.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image.html
Labels: Award: special achievement, Award: test coverage, Progress: approved

#237 ASI-209: [MFTF]: User searches stock images by keywords
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockSetConfigActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminSearchImagesOnModalActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertImageNotFoundAfterSearchFirstSymbolsActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockConfigData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserAccessesAdobeStockPanelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserSearchesStockImagesByKeywords.xml
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/toolbar.html
Labels: Progress: approved

#262 #258 : Add redirect_uri and locale to request url to IMS
  AdobeStockAsset/Test/Api/AssetRepository/SaveTest.php
  AdobeStockClient/Model/Config.php
  AdobeStockClient/composer.json
  AdobeStockClient/etc/config.xml
Labels: Progress: changes requested

#256 User filters images by image color Automation
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminApplyColorFilterValueActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminApplyNonValidColorValueToFilterActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertsFilterResultsActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockFilterSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/UserFiltersImagesByImageColor.xml
Labels: Progress: approved

#267 General code improvements
  AdobeStockAsset/Controller/Adminhtml/OAuth/Callback.php
  AdobeStockAsset/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/Config.php
  AdobeStockAsset/Model/Keyword.php
  AdobeStockAsset/Model/UserProfile.php
  AdobeStockAsset/Model/UserProfileRepository.php
  AdobeStockAsset/view/adminhtml/web/js/validate-api-key.js
  AdobeStockAssetApi/Api/Data/CategoryInterface.php
  AdobeStockAssetApi/Api/Data/CreatorInterface.php
  AdobeStockAssetApi/Api/Data/KeywordInterface.php
  AdobeStockAssetApi/Api/Data/UserProfileInterface.php
  AdobeStockClient/Model/SearchParametersProvider/Premium.php
  AdobeStockClient/Model/SearchParametersProvider/Words.php
  AdobeStockClient/Test/Unit/Model/ConfigTest.php
  AdobeStockClient/Test/Unit/Model/ConnectionFactoryTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/ContentTypeTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/IsolatedTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/OffensiveTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/OrientationTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/PaginationTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/SimpleFiltersTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/SortingTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/WordsTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProviderCompositeTest.php
  AdobeStockClient/etc/di.xml
  AdobeStockImage/Model/Storage.php
  AdobeStockImage/Plugin/Product/Gallery/Processor.php
  AdobeStockImage/Test/Unit/Model/StorageTest.php
  AdobeStockImageAdminUi/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButton.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/PremiumPrice/Options.php
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/authorization.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/masonry.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/model/messages.js
  AdobeStockImageAdminUi/view/adminhtml/web/panel.js
Labels: Progress: changes requested
