Repository magento/adobe-stock-integration, pull requests merged in 2019-11, with the labels that each got.

#615 Enhance AdobeStockAssetApi & AdobeStockClient test
  AdobeStockAssetApi/Api/GetAssetByIdInterface.php
  AdobeStockAssetApi/Api/SaveAssetInterface.php
  AdobeStockClient/Test/Unit/Model/ClientTest.php
  AdobeStockClient/Test/Unit/Model/ConfigTest.php
  AdobeStockClient/Test/Unit/Model/ConnectionFactoryTest.php
  AdobeStockClient/Test/Unit/Model/ConnectionWrapperTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/ContentTypeTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/IsolatedTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/MediaIdTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/OffensiveTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/OrientationTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/PaginationTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/PremiumTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/SimilarTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/SimpleFiltersTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/SortingTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProvider/WordsTest.php
  AdobeStockClient/Test/Unit/Model/SearchParametersProviderCompositeTest.php
  AdobeStockClient/Test/Unit/Model/StockFileToDocumentTest.php
Labels: Progress: approved

#606 [Unit test coverage] Covering the SaveAssetKeywords by Unit Test
  AdobeMediaGallery/Model/Keyword/Command/SaveAssetKeywords.php
  AdobeMediaGallery/Test/Unit/Model/Keyword/Command/SaveAssetKeywordsTest.php
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#613 Add Magento version to x-product header for Adobe Stock API requests
  AdobeStockClient/Model/Config.php
  AdobeStockClient/etc/config.xml
Labels: Progress: approved

#607 [MFTF coverage] Implementing the MFTF for "User cannot access stock images ...
  AdobeStockAdminUi/Test/Mftf/ActionGroup/AssertAdminFailedAuthenticationMessageActionGroup.xml
  AdobeStockAdminUi/Test/Mftf/Test/AdminCannotAccessStockImagesWithWrongCredentialsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockModalData.xml
Labels: Partner: Atwix, Progress: review, partners-contribution

#616 REFACTORING: granulate storage actions into two separate actions
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/Storage.php
  AdobeStockImage/Model/Storage/Delete.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/Storage/DeleteTest.php
  AdobeStockImage/Test/Unit/Model/Storage/SaveTest.php
  AdobeStockImage/etc/di.xml
  AdobeStockImageApi/Api/SaveImageInterface.php
Labels: Backend, Community Insider: Magecom, Progress: approved, community-insider-contribution

#617 Resolved issue #600
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#620 Added regex to sanitize filenames
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Partner: Zilker Technology, partners-contribution

#621 Resolved issue #581
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#579 #576 : Licensed overlay labels styling to match mockups
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: review

#625 Resolved issue #623
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/modal/adobe-modal-prompt-content.html
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#634 Improving the performance for saving the asset links.
  AdobeMediaGallery/Model/Keyword/Command/SaveAssetLinks.php
  AdobeMediaGallery/Test/Unit/Model/Keyword/Command/SaveAssetLinksTest.php
Labels: Partner: Atwix, Progress: approved, partners-contribution

#626 Resolved issue 200
  AdobeStockAdminUi/Test/Mftf/Test/AdminCannotAccessStockImagesWithWrongCredentialsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockClickSortActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridSortTest.xml
Labels: Partner: Zilker Technology, partners-contribution

#638 Resolved issue #586
  AdobeMediaGallery/Test/Unit/Model/Asset/Command/SaveTest.php
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#629 [WIP] Show error message in the grid's body
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminOpenMediaGalleryForPageNoEditorActionGroup.xml
  AdobeStockImageAdminUi/Test/Unit/Model/Listing/DataProviderTest.php
  AdobeUi/view/adminhtml/web/css/source/_module.less
  AdobeUi/view/adminhtml/web/js/components/grid/masonry.js
  AdobeUi/view/adminhtml/web/template/grid/masonry.html
Labels: Partner: Atwix, partners-contribution

#643 Enhance AdobeStockImageAdminUi tests
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/QuotaTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButtonTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/Listing/DataProviderTest.php
Labels: Progress: review

#647 DRY up the MFTF tests a little
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockOpenSearchModalActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminOpenMediaGalleryForPageNoEditorActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminUserHaveNoAccessToAdobeStockActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockACLTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
Labels: Progress: approved

#627 Resolved issue #453
  AdobeIms/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockSignedInViewCreditsActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockModalData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignedInCreditsVisibleTest.xml
Labels: MFTF coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#635 Added MFTF test that tests the see more from same model button
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelSeeMoreTest.xml
Labels: MFTF coverage

#655 Made test's <after/> node stateless
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignedInCreditsVisibleTest.xml
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#653 MFTF test tweaks, part two
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewAttributesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagesPreviewNavigationTest.xml
Labels: Progress: approved

#656 Close image preview on pagination change
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/images-grid-sizes.js
  AdobeUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Partner: Atwix, Progress: approved, partners-contribution

#654 REFACTORING: adjust commands to use the same strucutre
  AdobeMediaGallery/Model/Asset/Command/GetByPath.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Asset/LoadByIds.php
Labels: Community Insider: Magecom, community-insider-contribution

#648 Set modules and dependency versions
  AdobeIms/composer.json
  AdobeImsApi/composer.json
  AdobeMediaGallery/composer.json
  AdobeMediaGalleryApi/composer.json
  AdobeStockAdminUi/composer.json
  AdobeStockAsset/composer.json
  AdobeStockAssetApi/composer.json
  AdobeStockClient/composer.json
  AdobeStockClientApi/composer.json
  AdobeStockImage/composer.json
  AdobeStockImageAdminUi/composer.json
  AdobeStockImageApi/composer.json
  AdobeUi/composer.json
  _metapackage/composer.json
Labels: Progress: review

#661 Adjust Images listing declaration to pass integration tests
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
Labels: Progress: approved

#662 Added image preview responsiveness
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#663 Resolved issue 641
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#667 making mftf test annotations consistent
  AdobeStockAdminUi/Test/Mftf/Test/AdminAdobeStockConfigTest.xml
  AdobeStockAdminUi/Test/Mftf/Test/AdminCannotAccessStockImagesWithWrongCredentialsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockACLTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockColorFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridFiltersTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridSortTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewAttributesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagesPreviewNavigationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIsolatedFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockListingStateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockOrientationFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPageNumberTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPanelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPriceFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSafeContentFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavePreviewTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSeeMoreSeriesFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInSignOutTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignedInCreditsVisibleTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockTypeFilterTest.xml
Labels: MFTF coverage

#628 #575 : Licensed overlay labels are not updated when licensing and login/logout
  AdobeIms/Model/UserProfileRepository.php
  AdobeIms/view/adminhtml/web/js/signIn.js
  AdobeStockImage/etc/config.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
Labels: Progress: changes requested

#683 linking to test running documentation in the README
  README.md
Labels: Progress: approved

#682 Enabled travis for php 7.1
  .travis.yml
Labels: Progress: review

#693 AdminAdobeStockSafeContentFilterTest fails consistently
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSafeContentFilterTest.xml
Labels: Progress: changes requested

#681 Add PHPStan (level 2) to travis CI
  .travis.yml
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Controller/Adminhtml/User/Logout.php
  AdobeIms/Model/GetToken.php
  AdobeIms/Test/Unit/Controller/Adminhtml/OAuth/CallbackTest.php
  AdobeIms/Test/Unit/Model/GetImageTest.php
  AdobeIms/Test/Unit/Model/UserProfileRepositoryTest.php
  AdobeImsApi/Api/Data/UserProfileInterface.php
  AdobeStockAsset/Model/CategoryRepository.php
  AdobeStockAsset/Test/Api/AssetRepository/DeleteTest.php
  AdobeStockAsset/Test/Api/AssetRepository/GetByIdTest.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockImage/Test/Unit/Model/Extract/DocumentToAssetTest.php
  AdobeStockImage/Test/Unit/Model/GetImageListTest.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/SaveLicensedImageTest.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/SaveLicensed.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/LicenseTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/SaveLicensedTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/Listing/DataProviderTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/SignInConfigProviderTest.php
  AdobeStockImageAdminUi/Test/Unit/Ui/Component/Listing/Filter/ColorTest.php
Labels: Partner: Monsoon, Progress: changes requested, partners-contribution

#670 Resolved issue 641
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/overlay.html
Labels: Partner: Zilker Technology, Progress: review, partners-contribution

#699 Enable phpcs tests in travis CI
  .travis.yml
  AdobeIms/Model/FlushUserTokens.php
  AdobeIms/Model/GetImage.php
  AdobeIms/Model/LogOut.php
  AdobeIms/Test/Unit/Block/Adminhtml/SignInTest.php
  AdobeIms/Test/Unit/Controller/Adminhtml/User/ProfileTest.php
  AdobeIms/Test/Unit/Model/GetImageTest.php
  AdobeImsApi/Api/LogOutInterface.php
Labels: Partner: Monsoon, partners-contribution

#692 AdminAdobeStockImagePreviewKeywordsTest fails consistently && Static test fix
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/keywords.js
Labels: MFTF coverage, Progress: review

#700 use MFTF Credentials for storing sensitive variables
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImsPopupClickSignInActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockConfigData.xml
  AdobeStockImageAdminUi/Test/Mftf/README.md
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration.xml
Labels: MFTF coverage, Progress: approved

#695 Fix Search by keywords is broken
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/keywords.js
Labels: Progress: review

#674 #669 : Licensed overlay label is missing for just licensed images
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
Labels: Progress: changes requested

#716 Fixed overlay styling bug
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
Labels: Progress: approved

#633 [MFTF coverage] Adding MFTF coverage for saving the image preview with custom name
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminDeleteAdobeStockImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminSaveAdobeStockImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminImageIsVisibleInMediaGalleryActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockImageData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSaveImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminSavesTheImagePreviewWithNewNameTest.xml
Labels: MFTF coverage, Partner: Atwix, Progress: changes requested, partners-contribution

#719 Fixed Adobe configuration settings
  AdobeStockAdminUi/etc/adminhtml/system.xml
Labels: Partner: Zilker Technology, partners-contribution

#701 #704 Add check for non strict_types=1 files
  .travis.yml
  AdobeIms/registration.php
  AdobeImsApi/registration.php
  AdobeStockAdminUi/registration.php
  AdobeStockAsset/Test/Unit/Model/GetAssetByIdTest.php
  AdobeStockAsset/Test/Unit/Model/SaveAssetTest.php
  AdobeStockAsset/registration.php
  AdobeStockAssetApi/registration.php
  AdobeStockClient/Model/SearchParametersProvider/Premium.php
  AdobeStockClient/registration.php
  AdobeStockClientApi/registration.php
  AdobeStockImage/Test/Api/SearchExecuteTest.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImage/Test/Unit/Model/Storage/DeleteTest.php
  AdobeStockImage/Test/Unit/Model/Storage/SaveTest.php
  AdobeStockImage/registration.php
  AdobeStockImageAdminUi/registration.php
  AdobeStockImageApi/registration.php
Labels: Partner: Monsoon, Progress: approved, partners-contribution

#722 [WIP] Use image ID as a proposed filename for non-latin titles
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Partner: Atwix, partners-contribution

#729 MFTF test runs on travis
  .travis.yml
  AdobeStockAdminUi/Test/Mftf/Test/AdminAdobeStockConfigTest.xml
  AdobeStockAdminUi/Test/Mftf/Test/AdminCannotAccessStockImagesWithWrongCredentialsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-configuration.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-filters.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-grid.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-ims.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-keywords.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-preview.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-see-more.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockACLTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridFiltersTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridSortTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPanelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavePreviewTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInSignOutTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignedInCreditsVisibleTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminSavesTheImagePreviewWithNewNameTest.xml
  dev/tests/acceptance/.credentials
  dev/tests/acceptance/.env
  dev/tests/unit/phpunit.xml
  dev/travis/before_install.sh
  dev/travis/before_script.sh
  dev/travis/config/apache_virtual_host
Labels: Progress: approved

#714 Added MFTF test to verify License and Save button is visible
  .travis.yml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockImageData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockNotLicensedImageLicenseTest.xml
  dev/tests/acceptance/.env
  dev/travis/before_script.sh
Labels: Partner: Zilker Technology, partners-contribution

#639 MFTF Automation for: User locates licensed and uploaded image inside Media Gallery
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImagePreviewLocateActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavedLicensedImageLocateTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/actions.html
Labels: MFTF coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#713 Added MFTF test to locate previewed image
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewLocateTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/actions.html
Labels: Partner: Zilker Technology, partners-contribution

#671 [WIP] Possible MFTF test fail scenario discussion #660
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImsPopupClickSignInActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
Labels: MFTF coverage, Partner: Zilker Technology, Progress: approved, partners-contribution

#730 REFACTORING: adjust exception log process
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockClient/Model/StockFileToDocument.php
  AdobeStockImage/Model/Extract/AdobeStockAsset.php
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/Storage/Delete.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
Labels: Community Insider: Magecom, Progress: approved, community-insider-contribution

#741 Fixed usages of self
  AdobeIms/view/adminhtml/web/js/signIn.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#743 Log out all relevant files on travis during functional tests in case of failure
  .travis.yml
  dev/travis/before_script.sh
Labels: Progress: approved

#739 Added new logic to test API Key
  AdobeStockAdminUi/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAdminUi/view/adminhtml/templates/system/config/connection.phtml
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#747 Added tab separator styles
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Zilker Technology, partners-contribution

#740 Added empty API key error
  AdobeStockAdminUi/Block/Adminhtml/System/Config/TestConnection.php
  AdobeStockAdminUi/view/adminhtml/templates/system/config/connection.phtml
  AdobeStockAdminUi/view/adminhtml/web/js/connection.js
Labels: Partner: Zilker Technology, Progress: approved, partners-contribution

#759 REFACTORING: code quality improvement and general clean up
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Controller/Adminhtml/User/Logout.php
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/Model/Config.php
  AdobeIms/Model/FlushUserTokens.php
  AdobeIms/Model/GetAccessToken.php
  AdobeIms/Model/GetImage.php
  AdobeIms/Model/GetToken.php
  AdobeIms/Model/LogOut.php
  AdobeIms/Model/OAuth/TokenResponse.php
  AdobeIms/Model/UserAuthorized.php
  AdobeIms/Model/UserProfile.php
  AdobeIms/Model/UserProfileRepository.php
  AdobeIms/Test/Unit/Model/GetImageTest.php
  AdobeIms/Test/Unit/Model/UserProfileRepositoryTest.php
  AdobeImsApi/Api/ConfigInterface.php
  AdobeImsApi/Api/UserProfileRepositoryInterface.php
Labels: Backend, Community Insider: Magecom, Progress: approved, community-insider-contribution, enhancement

#712 User must be not able save image with same "File Name" twice in same directory…
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/Storage/SaveTest.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/Confirmation.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/License.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/Quota.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/SaveLicensed.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/Download.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/RelatedImages.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/ConfirmationTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/LicenseTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/QuotaTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/SaveLicensedTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/DownloadTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/RelatedImagesTest.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
  AdobeStockImageApi/Api/SaveImageInterface.php
Labels: Progress: review

#769 711 fix css in preview
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved, enhancement

#776 Update the phpdoc section for interfaces and classes
  AdobeIms/Block/Adminhtml/SignIn.php
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Controller/Adminhtml/User/Logout.php
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/Model/Config.php
  AdobeIms/Model/FlushUserTokens.php
  AdobeIms/Model/GetAccessToken.php
  AdobeIms/Model/GetImage.php
  AdobeIms/Model/GetToken.php
  AdobeIms/Model/LogOut.php
  AdobeIms/Model/OAuth/TokenResponse.php
  AdobeIms/Model/ResourceModel/UserProfile.php
  AdobeIms/Model/ResourceModel/UserProfile/Collection.php
  AdobeIms/Model/UserAuthorized.php
  AdobeIms/Model/UserProfile.php
  AdobeIms/Model/UserProfileRepository.php
  AdobeImsApi/Api/ConfigInterface.php
  AdobeImsApi/Api/Data/TokenResponseInterface.php
  AdobeImsApi/Api/Data/UserProfileInterface.php
  AdobeImsApi/Api/FlushUserTokensInterface.php
  AdobeImsApi/Api/GetAccessTokenInterface.php
  AdobeImsApi/Api/GetImageInterface.php
  AdobeImsApi/Api/GetTokenInterface.php
  AdobeImsApi/Api/LogOutInterface.php
  AdobeImsApi/Api/UserAuthorizedInterface.php
  AdobeImsApi/Api/UserProfileRepositoryInterface.php
Labels: Backend, Community Insider: Magecom, Progress: changes requested, community-insider-contribution, enhancement

#731 Move retrieving is_licensed attribute of images to a separate async request
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/Client/Files.php
  AdobeStockClient/Model/Config.php
  AdobeStockClient/Model/ConnectionWrapper.php
  AdobeStockClient/Test/Unit/Model/ClientTest.php
  AdobeStockClient/Test/Unit/Model/ConfigTest.php
  AdobeStockClient/Test/Unit/Model/ConnectionWrapperTest.php
  AdobeStockClient/composer.json
  AdobeStockClient/etc/config.xml
  AdobeStockClient/etc/di.xml
  AdobeStockClientApi/Api/Client/FilesInterface.php
  AdobeStockClientApi/Api/ConfigInterface.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetList.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/LicensedOverlay.php
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
Labels: Progress: review

#778 fix MFTF tests that previously relied on "Locate" button
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImagePreviewLocateActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/README.md
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockACLTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewLocateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavedLicensedImageLocateTest.xml
Labels: Progress: approved

#773 #768 : [1.1-develop] Introduce MediaGalleryUi module
  MediaGalleryUi/LICENSE.txt
  MediaGalleryUi/LICENSE_AFL.txt
  MediaGalleryUi/Model/Config.php
  MediaGalleryUi/README.md
  MediaGalleryUi/Test/Unit/Model/ConfigTest.php
  MediaGalleryUi/composer.json
  MediaGalleryUi/etc/adminhtml/system.xml
  MediaGalleryUi/etc/config.xml
  MediaGalleryUi/etc/module.xml
  MediaGalleryUi/modman
  MediaGalleryUi/registration.php
  _metapackage/composer.json
  modman
Labels: Progress: changes requested

#770 765 allocate space for related images
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
Labels: Progress: approved

#772 #720 : Save a licensed image, then delete, then open grid, 'locate' button is shown on preview
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/panel.js
Labels: Progress: approved

#777 Exclude Adobe stock related knowledge from the Adobe IMS
  AdobeIms/Model/Config.php
  AdobeIms/Test/Unit/Model/ConfigTest.php
  AdobeIms/etc/config.xml
  AdobeIms/etc/db_schema.xml
  AdobeIms/view/adminhtml/web/js/action/authorization.js
  AdobeIms/view/adminhtml/web/template/signIn.html
  AdobeStockAdminUi/etc/adminhtml/system.xml
  AdobeStockAsset/etc/di.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockConfigData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/signIn.html
Labels: Backend, Community Insider: Magecom, Progress: approved, community-insider-contribution, enhancement

#775 Show error when user is not able to login && Show image file name validation message in the confirmation popup
  AdobeIms/Model/GetToken.php
  AdobeIms/Test/Unit/Model/GetTokenTest.php
  AdobeIms/view/adminhtml/web/js/action/authorization.js
  AdobeStockImageAdminUi/view/adminhtml/templates/panel.phtml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/validation/validate-image-name.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/actions.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/signIn.html
Labels: Progress: changes requested

#785 removing test that attempt to license images
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockNotLicensedImageLicenseTest.xml
Labels: Progress: approved

#793 #738 : Long Adobe IMS account names show weirdly in Stock Search Grid
  AdobeIms/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved

#792 REFACTORING: adjust files service
  AdobeStockClient/Model/Client/Files.php
  AdobeStockClientApi/Api/Client/FilesInterface.php
Labels: Backend, Community Insider: Magecom, Progress: approved, community-insider-contribution, enhancement

#787 Add screenshot uploading support to Travis MFTF builds
  .travis.yml
  dev/travis/after_failure.sh
  dev/travis/script.sh
Labels: Progress: approved

#790 Serie Id and Model Id filters do not indicate applied values
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
Labels: Progress: approved

#800 A "500 Internat Server Error" appears in Developer Console each time when No records are found using search by filter(must be signed in Adobe Stock)
  AdobeIms/view/adminhtml/web/css/source/_module.less
  AdobeStockClient/Model/Client/Files.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetList.php
Labels: Progress: approved

#748 Search Adobe Stock button is not active on Edit Product Page in Admin
  AdobeStockImageAdminUi/Plugin/AddSearchButton.php
  AdobeStockImageAdminUi/Test/Unit/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButtonTest.php
  AdobeStockImageAdminUi/view/adminhtml/templates/panel.phtml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
Labels: has dependency

#789 REFACTORING: adjust phpdoc section
  AdobeStockAdminUi/Model/System/Config/Comment.php
  AdobeStockAsset/Model/AppendAttributes.php
  AdobeStockAsset/Model/Asset.php
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/Category.php
  AdobeStockAsset/Model/CategoryRepository.php
  AdobeStockAsset/Model/Config.php
  AdobeStockAsset/Model/Creator.php
  AdobeStockAsset/Model/CreatorRepository.php
  AdobeStockAsset/Model/GetAssetById.php
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Asset/LoadByIds.php
  AdobeStockAsset/Model/ResourceModel/Category/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/Save.php
  AdobeStockAsset/Model/SaveAsset.php
  AdobeStockAssetApi/Api/AssetRepositoryInterface.php
  AdobeStockAssetApi/Api/CategoryRepositoryInterface.php
  AdobeStockAssetApi/Api/ConfigInterface.php
  AdobeStockAssetApi/Api/CreatorRepositoryInterface.php
  AdobeStockAssetApi/Api/Data/AssetInterface.php
  AdobeStockAssetApi/Api/Data/CategoryInterface.php
  AdobeStockAssetApi/Api/Data/CreatorInterface.php
  AdobeStockAssetApi/Api/GetAssetByIdInterface.php
  AdobeStockAssetApi/Api/GetAssetListInterface.php
  AdobeStockAssetApi/Api/SaveAssetInterface.php
  AdobeStockClient/Model/Config.php
  AdobeStockClient/Model/ConnectionFactory.php
  AdobeStockClient/Model/ConnectionWrapper.php
  AdobeStockClient/Model/SearchParametersProviderComposite.php
  AdobeStockClient/Model/StockFileToDocument.php
  AdobeStockClientApi/Api/ConfigInterface.php
  AdobeStockClientApi/Api/Data/LicenseConfirmationInterface.php
  AdobeStockClientApi/Api/Data/UserQuotaInterface.php
Labels: Backend, Community Insider: Magecom, Progress: review, community-insider-contribution, enhancement

#803 795 images data provider for mediagalleryui
  MediaGalleryUi/Controller/Adminhtml/Index/Index.php
  MediaGalleryUi/Model/Filesystem/ImagesProvider.php
  MediaGalleryUi/Model/Listing/DataProvider.php
  MediaGalleryUi/etc/adminhtml/menu.xml
  MediaGalleryUi/etc/adminhtml/routes.xml
  MediaGalleryUi/etc/adminhtml/system.xml
  MediaGalleryUi/view/adminhtml/layout/media_gallery_index_index.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Progress: approved

#808 FEATURE: change location of the integration config related class
  AdobeIms/Test/Unit/Model/GetImageTest.php
  AdobeStockAsset/etc/di.xml
  AdobeStockAssetApi/Api/ConfigInterface.php
  AdobeStockImageAdminUi/Model/IsAdobeStockIntegrationEnabled.php
  AdobeStockImageAdminUi/Plugin/AddSearchButton.php
  AdobeStockImageAdminUi/Test/Unit/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButtonTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/IsAdobeStockIntegrationEnabledTest.php
Labels: Backend, Community Insider: Magecom, Progress: approved, community-insider-contribution, enhancement, unit tests coverage
