Repository magento/adobe-stock-integration, pull requests merged in 2020-06, with the labels that each got.

#1403 Added MediaGallery filter pool
  MediaGalleryUi/etc/di.xml
Labels: Progress: ready for delivery

#1402 [MFTF] Cover with MFTF filtering by Source media gallery && User is able to use bookmarks controls for filter views in Standalone Media
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryApplyFiltersActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryAssertActiveFiltersActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryAssertNoActiveFiltersAppliedActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryDeleteGridViewActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryExpandFilterActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGallerySaveCustomViewActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGallerySelectCustomBookmarksViewActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGallerySelectSourceFilterActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryAssertImageInGridActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryAssertImageNotExistsInTheGridActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryFiltersSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryFilterImagesBySourceTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGallerySaveFiltersStateTest.xml
Labels: MFTF coverage, Progress: approved

#1384 #1094 : [MFTF] User deletes images using Delete button
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryImageDeleteActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AssertAdminEnhancedMediaGalleryImageDeletedActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminMediaGalleryHeaderButtonsSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageContextMenuTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageFileTest.xml
Labels: Award: MFTF test coverage, Progress: changes requested

#1385 Replicate old media gallery behavior with current tree path
  MediaGalleryUi/Controller/Adminhtml/Directories/Create.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryFolderSelectActionGroup.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryAddCategoryImageFromTwoComponentsTest.xml
  MediaGalleryUi/etc/adminhtml/menu.xml
  MediaGalleryUi/view/adminhtml/web/js/directory/actions/createDirectory.js
  MediaGalleryUi/view/adminhtml/web/js/directory/actions/deleteDirectory.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: acceptance testing

#1394 Media gallery synchronization should consider file modification time && Performed media gallery && media content synchronization in batches
  MediaContentSynchronization/Model/Synchronize.php
  MediaContentSynchronizationCatalog/Model/Synchronizer/Category.php
  MediaContentSynchronizationCatalog/Model/Synchronizer/Product.php
  MediaContentSynchronizationCatalog/composer.json
  MediaContentSynchronizationCms/Model/Synchronizer/Block.php
  MediaContentSynchronizationCms/Model/Synchronizer/Page.php
  MediaContentSynchronizationCms/composer.json
  MediaGallerySynchronization/Model/CreateAssetFromFile.php
  MediaGallerySynchronization/Model/FetchBatches.php
  MediaGallerySynchronization/Model/FetchMediaStorageFileBatches.php
  MediaGallerySynchronization/Model/ResolveNonExistedAssets.php
  MediaGallerySynchronization/Model/Synchronize.php
  MediaGallerySynchronization/Model/SynchronizeFiles.php
  MediaGallerySynchronization/etc/di.xml
  MediaGallerySynchronizationApi/Model/FetchBatchesInterface.php
Labels: Progress: changes requested

#1416 #1404 - Removed default profile image feature
  AdobeIms/Block/Adminhtml/SignIn.php
  AdobeIms/Model/Config.php
  AdobeIms/Model/GetImage.php
  AdobeIms/Test/Unit/Block/Adminhtml/SignInTest.php
  AdobeIms/Test/Unit/Model/ConfigTest.php
  AdobeIms/etc/config.xml
  AdobeIms/view/adminhtml/web/js/signIn.js
  AdobeImsApi/Api/ConfigInterface.php
Labels: Award: bug fix, Progress: ready for delivery

#1418 Fixed scrolling to filters
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
Labels: Progress: ready for delivery

#1417 [MFTF] Cover filtering images by their keywords in Standalone Media Gallery
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGallerySearchByKeywordTest.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminAssertImageInStandaloneMediaGalleryActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/SearchStandaloneMediaGalleryAdminDataGridByKeywordActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryActionsSection.xml
Labels: Award: MFTF test coverage, Progress: review

#1414 #1407 - Fix Image cannot be located bug on root folder
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
Labels: Progress: ready for delivery

#1413 #1410 - Update images after folder deletion
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
  MediaGalleryUi/view/adminhtml/web/js/grid/masonry.js
Labels: Award: bug fix, Progress: ready for delivery

#1429 Disable related content tabs arrow navigation
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
Labels: Progress: ready for delivery

#1427 ACL. If user doesn't have permission to "Save Preview", the 'Search Adobe Stock' button is displayed but doesn't work
  AdobeStockImageAdminUi/Ui/Component/Listing/SearchAdobeStockButton.php
Labels: Progress: ready for delivery

#1433 #1432 :- Remove the "Get User Profile" ACL
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/etc/acl.xml
  README.md
Labels: Award: bug fix

#1455 Use the preidentified image for identification for ViewAdobeStockDetailsTests
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockExpandImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockImageData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminAdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryViewAdobeStockDetailsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewAdobeStockDetailsTest.xml
Labels: MFTF coverage, Progress: acceptance testing

#1434 Verify if current_tree_path folder exists on jstree initialization
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: ready for delivery

#1401 #1390 Add related content information to the delete asset warning
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImage.js
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
Labels: Partner: Atwix, Progress: ready for delivery, partners-contribution

#1471 magento/adobe-stock-integration #1459: Introduce a MediaGalleryRenditions module with width/hight system configuration fields
  MediaGalleryRenditions/LICENSE.txt
  MediaGalleryRenditions/LICENSE_AFL.txt
  MediaGalleryRenditions/Model/Config.php
  MediaGalleryRenditions/README.md
  MediaGalleryRenditions/composer.json
  MediaGalleryRenditions/etc/adminhtml/system.xml
  MediaGalleryRenditions/etc/config.xml
  MediaGalleryRenditions/etc/module.xml
  MediaGalleryRenditions/modman
  MediaGalleryRenditions/registration.php
  MediaGalleryRenditionsApi/LICENSE.txt
  MediaGalleryRenditionsApi/LICENSE_AFL.txt
  MediaGalleryRenditionsApi/Model/ConfigInterface.php
  MediaGalleryRenditionsApi/README.md
  MediaGalleryRenditionsApi/composer.json
  MediaGalleryRenditionsApi/etc/module.xml
  MediaGalleryRenditionsApi/modman
  MediaGalleryRenditionsApi/registration.php
  _metapackage/composer.json
  modman
Labels: Progress: acceptance testing

#1421 Addressing Discriminatory Language in Technology
  AdobeStockImage/Model/Storage/Save.php
  MediaGallerySynchronization/Model/FetchMediaStorageFileBatches.php
  MediaGalleryUi/Model/DeleteImage.php
  MediaGalleryUi/Model/Directories/FolderTree.php
Labels: 2.4.0-develop: dep

#1431 Fix Open Images uploaded outside of media gallery are not reflected …
  MediaGalleryIntegration/Plugin/SaveBaseCategoryImageInformation.php
  MediaGalleryIntegration/Plugin/SaveImageInformation.php
  MediaGalleryIntegration/composer.json
  MediaGalleryIntegration/etc/adminhtml/di.xml
  MediaGallerySynchronization/Model/Filesystem/SplFileInfoFactory.php
  MediaGalleryUi/Model/UploadImage.php
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryUploadCategoryImageTest.xml
  MediaGalleryUi/Test/Unit/Model/UploadImageTest.php
Labels: MFTF coverage, Priority: P1, Progress: ready for delivery

#1473 #1456 - Removed SelectModifierInterface and added CollectionProcessor
  AdobeStockImageAdminUi/Model/SearchCriteria/CollectionProcessor/JoinProcessor/IsLicensed.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/UnlicensedOverlay.php
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
  MediaGalleryUi/Model/FilterParametersProvider/Directory.php
  MediaGalleryUi/Model/Listing/DataProvider.php
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Directory.php
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Keyword.php
  MediaGalleryUi/Model/SelectModifierComposite.php
  MediaGalleryUi/Model/SelectModifierInterface.php
  MediaGalleryUi/Ui/Component/Filters/Type/Search.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1478 [2.0.0-master] Bugfixes
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/etc/acl.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockExpandImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockImageData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminAdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryViewAdobeStockDetailsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewAdobeStockDetailsTest.xml
  AdobeStockImageAdminUi/Ui/Component/Listing/SearchAdobeStockButton.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
  MediaGalleryIntegration/Plugin/SaveBaseCategoryImageInformation.php
  MediaGalleryIntegration/Plugin/SaveImageInformation.php
  MediaGalleryIntegration/composer.json
  MediaGalleryIntegration/etc/adminhtml/di.xml
  MediaGallerySynchronization/Model/Filesystem/SplFileInfoFactory.php
  MediaGalleryUi/Model/UploadImage.php
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryUploadCategoryImageTest.xml
  MediaGalleryUi/Test/Unit/Model/UploadImageTest.php
  README.md
Labels: 2.4.0-develop: :one:

#1470 Correct ACL permission on license proccess
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/getLicenseStatus.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Progress: ready for delivery

#1477 #1458 :- The Vertical images in "More from this series..." are not centered
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Award: bug fix, Progress: ready for delivery

#1472 Fix Escape doesn't close the Licensing confirmation message. Instead the Adobe Stock window is closed
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/getLicenseStatus.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/confirmation/license.js
Labels: Progress: ready for delivery

#1492 MQE-2194: fix mftf tests static check failures
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryViewAdobeStockDetailsTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryUploadCategoryImageTest.xml
Labels: Progress: acceptance testing

#1483 [2.0.0-develop] Remove obsolete content after content synchronization
  MediaContentSynchronization/Model/RemoveObsoleteContentAsset.php
  MediaContentSynchronization/Model/ResourceModel/GetOutdatedRelations.php
  MediaContentSynchronization/Model/Synchronize.php
  MediaContentSynchronization/composer.json
  MediaContentSynchronizationApi/Model/Entities.php
  MediaContentSynchronizationApi/Model/GetEntitiesInterface.php
  MediaContentSynchronizationApi/etc/di.xml
  MediaContentSynchronizationCatalog/etc/di.xml
  MediaContentSynchronizationCms/etc/di.xml
Labels: Priority: P1, Progress: ready for delivery, Severity: S1

#1520 fix long names UI issue in Media Gallery
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Frontend/UI, Progress: acceptance testing

#1521 add a dot at the end of the error message
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Frontend/UI, Progress: acceptance testing, Severity: S4

#1519 Update license action visibility based on overlay as is_lecensed column not exist anymore
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImageAssertLicenseButtonNotAvailableInMediaGalleryActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminAdobeStockImageAssertLicenseButtonMediaGalleryActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImageVerifyLicenseActionOnMediaGallery.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
Labels: MFTF coverage, Progress: changes requested

#1527 #1446 :- [MFTF] Backport the assertion correction to 1.0-develop
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIsolatedFilterTest.xml
Labels: Progress: acceptance testing

#1408 593: stub for the Adobe Stock API
  AdobeStockClient/Model/ConnectionFactory.php
  AdobeStockClient/Model/ConnectionWrapper.php
  AdobeStockClient/Test/Integration/Model/ClientTest.php
  AdobeStockClient/Test/Unit/Model/ConnectionWrapperTest.php
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminAdobeStockImageAttributesLocalizedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminNumberOfKeywordsInAdobeStockImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsTest.xml
  AdobeStockStub/LICENSE.txt
  AdobeStockStub/LICENSE_AFL.txt
  AdobeStockStub/Model/FileGenerator.php
  AdobeStockStub/Model/Handler.php
  AdobeStockStub/Model/HttpClient.php
  AdobeStockStub/Model/Modifier/IsApiCredentialsInvalid.php
  AdobeStockStub/Model/Modifier/LocalizeImageAttributes.php
  AdobeStockStub/Model/Modifier/ModifierInterface.php
  AdobeStockStub/Model/Modifier/NonExitedColor.php
  AdobeStockStub/Model/Modifier/SearchBySpecifiedMediaId.php
  AdobeStockStub/Model/Modifier/SearchBySpecifiedModelId.php
  AdobeStockStub/Model/Modifier/SearchBySpecifiedSerieId.php
  AdobeStockStub/Model/Modifier/SearchForSecondSymbols.php
  AdobeStockStub/Model/Modifier/SearchSpecificAssetToValidateKeywords.php
  AdobeStockStub/Model/Resolver.php
  AdobeStockStub/Model/StreamFactory.php
  AdobeStockStub/README.md
  AdobeStockStub/composer.json
  AdobeStockStub/etc/di.xml
  AdobeStockStub/etc/module.xml
  AdobeStockStub/modman
  AdobeStockStub/registration.php
  AdobeStockStub/view/adminhtml/web/images/1.png
  AdobeStockStub/view/adminhtml/web/images/2.png
  AdobeStockStub/view/adminhtml/web/images/3.png
  _metapackage/composer.json
  modman
Labels: Backend, Community Insider: Magecom, Progress: changes requested, community-insider-contribution

#1539 Fix static tests failures on 2.0-develop per new rules
  AdobeIms/Model/LogOut.php
  AdobeIms/view/adminhtml/web/css/source/_module.less
  AdobeIms/view/adminhtml/web/template/signIn.html
  AdobeStockAdminUi/Model/System/Config/Comment.php
  AdobeStockAdminUi/view/adminhtml/web/template/connection.html
  AdobeStockClient/Model/LicenseConfirmation.php
  AdobeStockClient/Test/Unit/Model/ClientTest.php
  AdobeStockClientApi/Api/Data/LicenseConfirmationInterface.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/Confirmation.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/ConfirmationTest.php
  AdobeStockImageAdminUi/view/adminhtml/web/template/signIn.html
  MediaGalleryUi/Ui/Component/Listing/Columns/SourceIconProvider.php
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
  MediaGalleryUi/view/adminhtml/web/template/grid/messages.html
Labels: Progress: acceptance testing

#1528 Use getMaxFileSize instead of a constant
  MediaGalleryUi/Ui/Component/ImageUploader.php
Labels: Progress: ready for delivery
