Repository magento/adobe-stock-integration, pull requests merged in 2020-03, with the labels that each got.

#992 improve media-gallery directory styles
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/images/d.png
Labels: Progress: approved

#974 Issue #965 Extract MediaGalleryIntegration module from the MediaGalleryUi
  MediaGalleryIntegration/LICENSE.txt
  MediaGalleryIntegration/LICENSE_AFL.txt
  MediaGalleryIntegration/Plugin/UpdateOpenDialogUrl.php
  MediaGalleryIntegration/Plugin/UpdateWysiwygOpenDialogUrl.php
  MediaGalleryIntegration/README.md
  MediaGalleryIntegration/Test/Unit/Plugin/UpdateOpenDialogUrlTest.php
  MediaGalleryIntegration/Test/Unit/Plugin/UpdateWysiwygOpenDialogUrlTest.php
  MediaGalleryIntegration/composer.json
  MediaGalleryIntegration/etc/adminhtml/di.xml
  MediaGalleryIntegration/etc/module.xml
  MediaGalleryIntegration/modman
  MediaGalleryIntegration/registration.php
  MediaGalleryUi/etc/adminhtml/di.xml
  _metapackage/composer.json
  modman
Labels: Partner: Atwix, Progress: review, partners-contribution

#998 #988: Fixed - the "Couldn't log you in" message appears twice
  AdobeIms/view/adminhtml/web/js/action/authorization.js
Labels: Partner: Atwix, partners-contribution

#993 #891: [Bug] Attempt to license image the second time if user is not logged in when initiating the licensing process
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Award: bug fix, Progress: approved

#997 FEATURE: media content modules
  MediaContent/LICENSE.txt
  MediaContent/LICENSE_AFL.txt
  MediaContent/Model/AssignAsset.php
  MediaContent/Model/GetAssetsUsedInContent.php
  MediaContent/Model/GetContentWithAsset.php
  MediaContent/Model/UnassignAsset.php
  MediaContent/README.md
  MediaContent/composer.json
  MediaContent/etc/db_schema.xml
  MediaContent/etc/db_schema_whitelist.json
  MediaContent/etc/di.xml
  MediaContent/etc/module.xml
  MediaContent/modman
  MediaContent/registration.php
  MediaContentApi/Api/AssignAssetInterface.php
  MediaContentApi/Api/GetAssetsUsedInContentInterface.php
  MediaContentApi/Api/GetContentWithAssetInterface.php
  MediaContentApi/Api/UnassignAssetInterface.php
  MediaContentApi/LICENSE.txt
  MediaContentApi/LICENSE_AFL.txt
  MediaContentApi/README.md
  MediaContentApi/composer.json
  MediaContentApi/etc/module.xml
  MediaContentApi/modman
  MediaContentApi/registration.php
  _metapackage/composer.json
  modman
Labels: Backend, Community Insider: Magecom, Progress: changes requested, community-insider-contribution

#1013 Provide Delete Folder functionality for DirectoryTree
  MediaContent/etc/module.xml
  MediaGalleryUi/Controller/Adminhtml/Directories/Delete.php
  MediaGalleryUi/Model/Directories/DeleteByPath.php
  MediaGalleryUi/Ui/Component/DirectoriesTree.php
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: approved

#1019 Fixed the issue with length attribute for varchar column
  MediaContent/etc/db_schema.xml
Labels: Award: bug fix, Partner: Atwix, partners-contribution

#1022 #1012 : Add Delete Selcted button to media gallery page actions
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
Labels: Award: category of expertise, Progress: approved

#1020 Provide functionality to create folders in media gallery
  MediaContent/composer.json
  MediaGalleryUi/Controller/Adminhtml/Directories/Create.php
  MediaGalleryUi/Model/Directories/CreateByPath.php
  MediaGalleryUi/Ui/Component/DirectoriesTree.php
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: review

#1018 #issue-904 Added view details slide panel for an image in Media Gallery
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
  AdobeStockImageAdminUi/view/adminhtml/layout/media_gallery_index_index.xml
  AdobeStockImageAdminUi/view/adminhtml/templates/image_details/adobe_stock.phtml
  AdobeStockImageAdminUi/view/adminhtml/web/template/image/adobe-stock-image-details.html
  MediaGalleryUi/Controller/Adminhtml/Image/Details.php
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/view/adminhtml/layout/media_gallery_index_index.xml
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
  MediaGalleryUi/view/adminhtml/web/template/image/actions.html
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
Labels: Award: advanced, Partner: Atwix, Progress: approved, partners-contribution

#1017 magento/adobe-stock-integration#1015 Adobe Stock grid doesn't load with disabled `Enhanced Media Gallery`
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
  AdobeStockImageAdminUi/view/adminhtml/layout/media_gallery_index_index.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
Labels: Progress: approved

#1031 Add follow symlinks to support linked folders
  MediaGalleryUi/Model/ImagesIndexer.php
Labels: Progress: approved

#1029 REFACTORING: clean up the module code base and refactoring to allow static tests passing
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/LicenseTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/QuotaTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/SaveLicensedTest.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/UnlicensedOverlay.php
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
Labels: Community Insider: Magecom, Progress: approved, community-insider-contribution

#1037 Remove ability to multiselect nodes in directoryTree
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: approved

#1036 #issue-1027 Fixed broken Media gallery layout in Safari browser
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#1038 #issue-990 Adjusted the logic of clicking on three dots and selecting highlighted image
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
Labels: Award: bug fix, Partner: Atwix, partners-contribution

#1024 [MFTF] tests stabilization
  AdobeStockAdminUi/Test/Mftf/Test/AdminCannotAccessStockImagesWithWrongCredentialsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImsPopupClickSignInActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridSortTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIncorrectSecretSignInTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLicensedImageViewLabelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSaveLicenseWithSavedPreviewTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSaveLicensedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavedLicensedImageLocateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInSignOutTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignedInCreditsVisibleTest.xml
Labels: Progress: changes requested

#1040 [MFTF] Selector ".adobe-profile-image-small" didn't find in some tests
  AdobeStockAdminUi/Test/Mftf/Test/AdminAdobeStockConfigTest.xml
  AdobeStockAdminUi/Test/Mftf/Test/AdminCannotAccessStockImagesWithWrongCredentialsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockAssertUserLoggedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImsPopupClickSignInActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockImageData.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-filters.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-grid.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-ims-signed.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-ims.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-keywords.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-license.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-preview.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-see-more.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockACLTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockColorFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridBookmarksTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridFiltersTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridSortTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewAttributesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewKeywordsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewLocateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagesPreviewNavigationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIncorrectSecretSignInTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIsolatedFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLicensedImageViewLabelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockListingStateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockNotLicensedImageLicenseTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockOrientationFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPageNumberTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPanelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockPriceFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSafeContentFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSaveLicensedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavePreviewTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavedLicensedImageLocateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSearchTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInACLTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInSignOutTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignedInCreditsVisibleTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockTypeFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminSavesTheImagePreviewWithNewNameTest.xml
  AdobeStockImageAdminUi/etc/config.xml
Labels: Progress: approved

#1039 [MFTF] Cover test scenario #458
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminSaveAdobeStockImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminViewsStockLicenseStatusTest.xml
Labels: Progress: review

#1056 #1054: change notification message at the popup on folder delete from…
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
Labels: Award: bug fix, Community Insider: Magecom, community-insider-contribution

#1016 FEATURE: Save media asset relations when content is saved
  MediaContent/Model/ContentProcessor.php
  MediaContent/Model/ExtractAssetFromContent.php
  MediaContent/Model/GetAssetsUsedInContent.php
  MediaContent/Model/ModelProcessor.php
  MediaContent/Observer/CatalogCategory.php
  MediaContent/Observer/CatalogProduct.php
  MediaContent/Observer/CmsBlock.php
  MediaContent/Observer/CmsPage.php
  MediaContent/composer.json
  MediaContent/etc/db_schema.xml
  MediaContent/etc/db_schema_whitelist.json
  MediaContent/etc/di.xml
  MediaContent/etc/events.xml
  MediaContentApi/Api/GetAssetsUsedInContentInterface.php
Labels: Award: advanced, Backend, Community Insider: Magecom, Progress: review, community-insider-contribution

#1053 Fixed the issue with unknown characters are displayed instead of three dots
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#1045 #issue-1042 Fixed sort order of media gallery grid buttons
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#1008 #963 : Introduce a dedicated Media Gallery page
  AdobeStockImageAdminUi/view/adminhtml/layout/media_gallery_media_index.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/panel.js
  MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
  MediaGalleryUi/Controller/Adminhtml/Media/Index.php
  MediaGalleryUi/etc/adminhtml/menu.xml
  MediaGalleryUi/view/adminhtml/layout/media_gallery_media_index.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Award: category of expertise, Progress: review

#1021 #1010: Image size is not passed to image-uploader when inserting an image from new media gallery
  MediaGalleryUi/Model/AssetIndexer.php
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
Labels: Award: complex, Progress: approved, has dependency

#1033 [MFTF] Cover test scenario #1006
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminSeeMoreFromSeriesTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
Labels: Progress: changes requested

#1025 Do not show excluded directories and images in the media gallery
  MediaGalleryUi/Model/Directories/ExcludedDirectories.php
  MediaGalleryUi/Model/Directories/FolderTree.php
  MediaGalleryUi/Model/FilesIndexer.php
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
Labels: Progress: changes requested

#1060 Fixed LESS file static tests
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1067 Issue 1052 fix view details image size
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Award: bug fix, Partner: Atwix, Progress: approved, partners-contribution

#1069 [WIP]skip AdminAdobeStockIncorrectSecretSignInTest
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIncorrectSecretSignInTest.xml
Labels: Progress: approved

#1057 #1049: add author and creator Adobe Stock data to the detils info
  AdobeStockAsset/Model/ResourceModel/Category/Command/LoadById.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/LoadById.php
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
Labels: Community Insider: Magecom, Critical, community-insider-contribution

#1058 1048: adjust folder create error message to the Magento standard mesages
  MediaGalleryUi/Controller/Adminhtml/Directories/Create.php
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
Labels: Community Insider: Magecom, community-insider-contribution

#1063 Improve three dots style for all browsers, bugfixes
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/images/3-dots.png
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
Labels: Progress: approved

#1076 Issue 1051 Added Add Image functionality for Media Gallery View Details popup
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/view/adminhtml/layout/media_gallery_index_index.xml
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
Labels: Partner: Atwix, Progress: approved, partners-contribution

#1035 UnitTests: cover with Unit tests base MediaContent module data storage commands
  MediaContent/Model/GetContentWithAsset.php
  MediaContent/Test/Unit/Model/AssignAssetTest.php
  MediaContent/Test/Unit/Model/GetAssetsusedInContentTest.php
  MediaContent/Test/Unit/Model/GetContentWithAssetTest.php
  MediaContent/Test/Unit/Model/UnassignAssetTest.php
Labels: Backend, Community Insider: Magecom, Progress: review, community-insider-contribution, unit tests coverage

#1086 Fix broked standalone media gallery, add conteiner class to match styles
  MediaGalleryUi/view/adminhtml/layout/media_gallery_media_index.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved
