Repository magento/adobe-stock-integration, pull requests merged in 2020-04, with the labels that each got.

#1088 Add folders functionality && image-details actions to standalone media gallery page
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/layout/media_gallery_media_index.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
Labels: Progress: approved

#987 DI configuration for the content type option provider
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ContentType/Options.php
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
Labels: Progress: approved

#1091 Exclude dot directories and images in it from mediaGallery && Page builder doesn't load images from Enhanced Media gallery, instead the "old" Media Gallery is used
  MediaGalleryIntegration/Plugin/UpdateOpenDialogUrlPageBuilder.php
  MediaGalleryIntegration/etc/adminhtml/di.xml
  MediaGalleryUi/etc/di.xml
Labels: Progress: review

#1080 Issue: 914 - Image Upload
  MediaGalleryUi/Controller/Adminhtml/Image/Upload.php
  MediaGalleryUi/Model/Filesystem/SplFileInfoFactory.php
  MediaGalleryUi/Model/UploadImage.php
  MediaGalleryUi/Ui/Component/ImageUploader.php
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
  MediaGalleryUi/view/adminhtml/web/template/image-uploader.html
Labels: Progress: approved

#1107 Trigger media gallery reindex when Enhanced Media Gallery is enabled in configuration
  MediaGalleryUi/Plugin/MediaGalleryIndexerTrigger.php
  MediaGalleryUi/etc/adminhtml/di.xml
Labels: Progress: approved

#1034 #912: Fixed image located in the media gallery
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
Labels: Award: advanced, Critical, Partner: Atwix, Progress: changes requested, partners-contribution

#1075 Fix add Selected button, to abjust working with wysiwyg and widgets
  MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
  MediaGalleryUi/view/adminhtml/layout/media_gallery_index_index.xml
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/insertImageAction.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
Labels: Critical, Progress: review

#1111 #913 - save image for new gallery and select image after save
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
Labels: Critical, Partner: Atwix, Progress: approved, partners-contribution

#1116 Fix undefined error dorectories(), and Add Image action on view
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Progress: approved

#1064 [MFTF] Cover test scenarios #1046, #1047
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockAssertFolderSelectedActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryAssertFolderDoesNotExistActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryAssertFolderNameActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryCreateNewFolderActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryFolderDeleteActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryFolderSelectActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryOpenNewFolderFormActionGroup.xml
  MediaGalleryUi/Test/Mftf/Data/AdminMediaGalleryFolderData.xml
  MediaGalleryUi/Test/Mftf/Section/AdminMediaGalleryFolderSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryCreateDeleteFolderTest.xml
Labels: Progress: changes requested

#1100 Added image Type field to the image details slide panel
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/etc/adminhtml/di.xml
Labels: Progress: changes requested

#1110 Fix Longs names on modals poups
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
Labels: Progress: approved

#1109 Add functional to remove Add Image button in Standalone Media Gallery
  MediaGalleryUi/view/adminhtml/layout/media_gallery_media_index.xml
  MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml
Labels: Progress: changes requested

#938 #906 Add sorting for the Media Gallery
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminAdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavedLicensedImageLocateTest.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/sorting.js
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/template/grid/toolbar.html
Labels: Award: complex, Progress: changes requested

#1122 Replaced DataExtractor with ObjectProcessor
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Category/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/Save.php
  AdobeStockAsset/Model/SaveAsset.php
  AdobeStockAsset/Test/Unit/Model/SaveAssetTest.php
Labels: Asset Component, Backend, Progress: approved

#1130 FEATURE: unit tests for MediaGalleryUi upload image functionality
  MediaGalleryUi/Model/Filesystem/SplFileInfoFactory.php
  MediaGalleryUi/Model/UploadImage.php
  MediaGalleryUi/Test/Unit/Model/UploadImageTest.php
Labels: Backend, Community Insider: Magecom, Event: Global-Contribution-Day, MediaGalleryUi Component, Progress: approved, community-insider-contribution, unit tests coverage

#1113 hotfix: Correct pattern to exclude directores started with dots .thumbnail
  MediaGalleryUi/Model/Directories/FolderTree.php
  MediaGalleryUi/Model/FilesIndexer.php
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
  MediaGalleryUi/view/adminhtml/web/template/image-uploader.html
Labels: Progress: approved

#1140 Correct Page Builder plugin, with undefined key
  MediaGalleryIntegration/Plugin/UpdateOpenDialogUrlPageBuilder.php
Labels: Progress: approved

#1152 Skip failing tests
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSaveLicensedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockTryLicenseAlreadyLicensedImageTest.xml
Labels: Progress: approved

#1087 1083: fix adobe stock asset save action
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SaveImageFile.php
  AdobeStockImage/Model/SaveMediaGalleryAsset.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/SaveImageFileTest.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
  AdobeStockImage/Test/Unit/Model/Storage/SaveTest.php
  AdobeStockImage/etc/di.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminSeeMoreFromSeriesTest.xml
  MediaGalleryUi/Model/UpdateAssetInGrid.php
Labels: Award: complex, Award: test coverage, Community Insider: Magecom, Critical, Event: Global-Contribution-Day, Progress: review, community-insider-contribution

#1129 Issue 1028 - Fixed issue with asset license info loading
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  dev/tests/js/jasmine/tests/app/code/Magento/AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.test.js
Labels: Event: Global-Contribution-Day, Progress: approved, in progress

#1082 #issue-1074 Added image selecting/highlighting when clicking on the grey area or license label
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
Labels: Partner: Atwix, Progress: changes requested, partners-contribution

#1118 An image remains selected when switching between folders
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryFolderSelectActionGroup.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
Labels: Progress: approved

#1127 Adding a custom "per page" and switching to another View leads to "per page" braking and an uncaught type error in dev console
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/images-grid-sizes.js
Labels: Progress: approved

#1131 FIX: clean up MediaGallery module
  MediaGalleryIntegration/Plugin/UpdateOpenDialogUrlPageBuilder.php
  MediaGalleryUi/Controller/Adminhtml/Directories/Create.php
  MediaGalleryUi/Model/Directories/FolderTree.php
  MediaGalleryUi/Plugin/MediaGalleryIndexerTrigger.php
  MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
Labels: Backend, Cleanup, Community Insider: Magecom, Event: Global-Contribution-Day, MediaGalleryUi Component, Progress: approved, community-insider-contribution

#1138 Improve styles for internet explorer & EDGE
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved

#1154 Add filtering by "Source" to Standalone Media Gallery
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Source/Options.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/Model/UpdateAssetInGrid.php
Labels: Progress: approved

#1159 The "See more" button doesn't work when More images are loaded and the same image is previewed again
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
Labels: Progress: approved

#1165 The folders structure is not updated after deleting, the focus remains on deleted folder
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Progress: approved

#1166 Fix save image inserted to wysiwyg as directive with media url
  MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/insertImageAction.js
Labels: Critical, Progress: approved

#1181 Enable MediaGallery to tinyMCE3
  MediaGalleryIntegration/Plugin/UpdateWysiwygDialogUrlTinyMce.php
  MediaGalleryIntegration/composer.json
  MediaGalleryIntegration/etc/adminhtml/di.xml
Labels: Progress: approved

#1169 [MFTF] Fix `See More` tests
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminSeeMoreFromSeriesTest.xml
Labels: Progress: approved

#1202 Batch PRs delivery
  AdobeStockImage/Model/AssetIndexer.php
  AdobeStockImage/Model/Plugin/AddLicenseDataToAsset.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SetLicensedInMediaGalleryGrid.php
  AdobeStockImage/Test/Unit/Model/AssetIndexerTest.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/SetLicensedInMediaGalleryGridTest.php
  AdobeStockImage/composer.json
  AdobeStockImage/etc/db_schema.xml
  AdobeStockImage/etc/db_schema_whitelist.json
  AdobeStockImage/etc/di.xml
  AdobeStockImage/etc/module.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameModelSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImagePreviewSameSeriesSeeMoreTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockIsolatedFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSafeContentFilterTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminViewsStockLicenseStatusTest.xml
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/UnlicensedOverlay.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/licenseImage.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/mediaGallery/grid/columns/image/licenseActions.html
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/Model/ResourceModel/Grid/Asset.php
  MediaGalleryUi/Model/ResourceModel/Grid/Asset/Collection.php
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/Model/UpdateAssetKeywordsInGrid.php
  MediaGalleryUi/Plugin/UpdateAssetInGrid.php
  MediaGalleryUi/Plugin/UpdateAssetKeywordsInGrid.php
  MediaGalleryUi/Ui/Component/Listing/Provider.php
  MediaGalleryUi/composer.json
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/layout/media_gallery_media_index.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
  MediaGalleryUi/view/adminhtml/web/template/image-uploader.html
Labels: in progress

#1160 License an image from the Media Gallery
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/licenseImage.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/mediaGallery/grid/columns/image/licenseActions.html
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
Labels: Critical, Progress: changes requested

#1206 Fix locate image After save && license image three dots from standalone page && gray overlay on delete action && license button visibility
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImage.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
Labels: Critical, Progress: approved

#1204 Hot fix undefined index
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminViewsStockLicenseStatusTest.xml
  MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
Labels: Critical, Progress: review

#1215 ECP-530: Static test to detect external project dependencies
  MediaGalleryIntegration/composer.json
Labels: Progress: changes requested

#1227 Code cleanup and phpunit 8 support
  AdobeIms/Model/FlushUserTokens.php
  AdobeIms/Model/UserAuthorized.php
  AdobeIms/Model/UserProfileRepository.php
  AdobeIms/Observer/FlushUsersTokensObserver.php
  AdobeIms/Test/Unit/Controller/Adminhtml/OAuth/CallbackTest.php
  AdobeIms/Test/Unit/Controller/Adminhtml/User/LogoutTest.php
  AdobeIms/Test/Unit/Controller/Adminhtml/User/ProfileTest.php
  AdobeIms/Test/Unit/Model/GetImageTest.php
  AdobeIms/Test/Unit/Model/GetTokenTest.php
  AdobeIms/Test/Unit/Observer/FlushUsersTokensObserverTest.php
  AdobeStockAdminUi/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAdminUi/view/adminhtml/templates/system/config/connection.phtml
  AdobeStockAsset/Model/AppendAttributes.php
  AdobeStockAsset/Model/CategorySearchResults.php
  AdobeStockAsset/Model/CreatorSearchResults.php
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockAsset/Model/ResourceModel/Command/InsertIgnore.php
  AdobeStockAsset/Test/Unit/Model/CreatorRepositoryTest.php
  AdobeStockAsset/Test/Unit/Model/GetAssetByIdTest.php
  AdobeStockAsset/Test/Unit/Model/SaveAssetTest.php
  AdobeStockClient/Model/Client.php
  AdobeStockClient/Model/Config.php
  AdobeStockClient/Model/ConnectionWrapper.php
  AdobeStockClient/Model/SearchParametersProvider/ContentType.php
  AdobeStockClient/Model/SearchParametersProvider/Isolated.php
  AdobeStockClient/Model/SearchParametersProvider/Offensive.php
  AdobeStockClient/Test/Unit/Model/ConnectionWrapperTest.php
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SaveImageFile.php
  AdobeStockImage/Model/SaveMediaGalleryAsset.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
  AdobeStockImage/composer.json
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Image.php
  AdobeStockImageAdminUi/view/adminhtml/templates/panel.phtml
  MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
  MediaGalleryUi/Controller/Adminhtml/Image/Details.php
  MediaGalleryUi/Controller/Adminhtml/Index/Index.php
  MediaGalleryUi/Controller/Adminhtml/Media/Index.php
  MediaGalleryUi/Model/DeleteImageByAssetId.php
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/Ui/Component/ImageUploader.php
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml
Labels: Critical, in progress

#1161 #911 : Add "Used in" section to media gallery image details
  MediaGalleryUi/Model/GetAssetsUsedIn.php
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
  MediaGalleryUiApi/Api/GetAssetUsedInInterface.php
Labels: Award: complex, Progress: review, has dependency, next

#1158 Updated MediaGallery modules and marked as API
  AdobeStockAssetApi/Model/Asset/Command/LoadByIdsInterface.php
  AdobeStockImage/Model/Extract/Keywords.php
  AdobeStockImage/Model/Extract/MediaGalleryAsset.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SaveImageFile.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/composer.json
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminViewsStockLicenseStatusTest.xml
  MediaGallerySynchronization/Model/CreateAssetFromFile.php
  MediaGallerySynchronization/Model/Directories/ExcludedDirectories.php
  MediaGallerySynchronization/Model/Synchronize.php
  MediaGallerySynchronization/etc/di.xml
  MediaGallerySynchronizationApi/Api/ExcludedDirectoriesInterface.php
  MediaGalleryUi/Controller/Adminhtml/Directories/Create.php
  MediaGalleryUi/Controller/Adminhtml/Directories/Delete.php
  MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
  MediaGalleryUi/Model/DeleteImageByAssetId.php
  MediaGalleryUi/Model/Directories/CreateByPath.php
  MediaGalleryUi/Model/Directories/DeleteByPath.php
  MediaGalleryUi/Model/Directories/FolderTree.php
Labels: has dependency, in progress

#1235 Media Content Moved to Magento and Used In functionality
  MediaContent/LICENSE.txt
  MediaContent/LICENSE_AFL.txt
  MediaContent/Model/AssignAsset.php
  MediaContent/Model/ContentProcessor.php
  MediaContent/Model/ExtractAssetFromContent.php
  MediaContent/Model/GetAssetsUsedInContent.php
  MediaContent/Model/GetContentWithAsset.php
  MediaContent/Model/ModelProcessor.php
  MediaContent/Model/UnassignAsset.php
  MediaContent/Observer/CatalogCategory.php
  MediaContent/Observer/CatalogProduct.php
  MediaContent/Observer/CmsBlock.php
  MediaContent/Observer/CmsPage.php
  MediaContent/README.md
  MediaContent/Test/Unit/Model/AssignAssetTest.php
  MediaContent/Test/Unit/Model/GetAssetsusedInContentTest.php
  MediaContent/Test/Unit/Model/GetContentWithAssetTest.php
  MediaContent/Test/Unit/Model/UnassignAssetTest.php
  MediaContent/composer.json
  MediaContent/etc/db_schema.xml
  MediaContent/etc/db_schema_whitelist.json
  MediaContent/etc/di.xml
  MediaContent/etc/events.xml
  MediaContent/etc/module.xml
  MediaContent/modman
  MediaContent/registration.php
  MediaContentApi/Api/AssignAssetInterface.php
  MediaContentApi/Api/GetAssetsUsedInContentInterface.php
  MediaContentApi/Api/GetContentWithAssetInterface.php
  MediaContentApi/Api/UnassignAssetInterface.php
  MediaContentApi/LICENSE.txt
  MediaContentApi/LICENSE_AFL.txt
  MediaContentApi/README.md
  MediaContentApi/composer.json
  MediaContentApi/etc/module.xml
  MediaContentApi/modman
  MediaContentApi/registration.php
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/composer.json
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
  _metapackage/composer.json
  modman
Labels: in progress

#1186 Remove Page Builder dependency
  MediaGalleryIntegration/Model/OpenDialogUrlProvider.php
  MediaGalleryIntegration/Plugin/UpdateOpenDialogUrl.php
  MediaGalleryIntegration/Plugin/UpdateOpenDialogUrlPageBuilder.php
  MediaGalleryIntegration/Plugin/UpdateWysiwygDialogUrlTinyMce.php
  MediaGalleryIntegration/Plugin/UpdateWysiwygOpenDialogUrl.php
  MediaGalleryIntegration/Test/Unit/Plugin/UpdateOpenDialogUrlTest.php
  MediaGalleryIntegration/Test/Unit/Plugin/UpdateWysiwygOpenDialogUrlTest.php
  MediaGalleryIntegration/composer.json
  MediaGalleryIntegration/etc/adminhtml/di.xml
  MediaGalleryIntegration/etc/module.xml
  MediaGalleryUi/view/adminhtml/layout/media_gallery_media_index.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/insertImageAction.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
Labels: Critical, Progress: ready for delivery, has dependency, merge in progress

#1247 Fix Could not synchronize assets saved from Adobe Stock
  MediaGallerySynchronization/Model/CreateAssetFromFile.php
Labels: Progress: ready for delivery, merge in progress

#1246 Open in Media Gallery is available for deleted image
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Progress: ready for delivery, merge in progress

#1244 Switched to MediaGallery bulk api and resolved complexity
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Model/LogIn.php
  AdobeIms/Test/Unit/Controller/Adminhtml/OAuth/CallbackTest.php
  AdobeIms/etc/di.xml
  AdobeImsApi/Api/LogInInterface.php
  AdobeStockAsset/Test/Unit/Model/CreatorRepositoryTest.php
  AdobeStockAsset/Test/_files/asset.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SaveKeywords.php
  AdobeStockImage/Model/SaveMediaGalleryAsset.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/SaveLicensed.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/Download.php
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
  AdobeStockImageAdminUi/Plugin/AddSearchButton.php
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
  MediaGallerySynchronization/Model/SynchronizeFiles.php
  MediaGalleryUi/Controller/Adminhtml/Image/Details.php
  MediaGalleryUi/Controller/Adminhtml/Image/Upload.php
  MediaGalleryUi/Model/AssetDetailsProvider/CreatedAt.php
  MediaGalleryUi/Model/AssetDetailsProvider/Height.php
  MediaGalleryUi/Model/AssetDetailsProvider/Size.php
  MediaGalleryUi/Model/AssetDetailsProvider/Type.php
  MediaGalleryUi/Model/AssetDetailsProvider/UpdatedAt.php
  MediaGalleryUi/Model/AssetDetailsProvider/UsedIn.php
  MediaGalleryUi/Model/AssetDetailsProvider/Width.php
  MediaGalleryUi/Model/AssetDetailsProviderInterface.php
  MediaGalleryUi/Model/AssetDetailsProviderPool.php
  MediaGalleryUi/Model/GetDetailsByAssetId.php
  MediaGalleryUi/Model/GetImageDetailsByAssetId.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AssertAdminImageIsVisibleInMediaGalleryActionGroup.xml
  MediaGalleryUi/Ui/Component/Listing/Provider.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
  MediaGalleryUiApi/Api/ConfigInterface.php
Labels: Progress: ready for delivery, merge in progress

#1236 FIX: use relative path during image directory ignore list validation
  MediaGallerySynchronization/Model/Synchronize.php
Labels: Backend, Community Insider: Magecom, Progress: ready for delivery, community-insider-contribution, merge in progress

#1231 An image remains selected when switching between folders
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
Labels: Progress: ready for delivery, merge in progress

#1224 Utilizing Files API implementation of SDK
  AdobeStockClient/Model/Client/Files.php
  AdobeStockClient/Model/FilesRequestFactory.php
  AdobeStockClient/Test/Unit/Model/Client/Files/CurlRequestFailed.php
  AdobeStockClient/Test/Unit/Model/Client/Files/CurlResultContainsEmptyFilesTest.php
  AdobeStockClient/Test/Unit/Model/Client/Files/CurlResultSuccessFilesExistsTest.php
  AdobeStockClient/Test/Unit/Model/Client/Files/EmptyIdsTest.php
  AdobeStockClient/Test/Unit/Model/Client/Files/FilesTest.php
  AdobeStockClientApi/Api/ConfigInterface.php
Labels: Asset Component, Backend, Community Insider: Magecom, Progress: ready for delivery, community-insider-contribution, merge in progress

#1250 Migrate Unit Tests to phpunit 8
  AdobeIms/Test/Unit/Block/Adminhtml/SignInTest.php
  AdobeIms/Test/Unit/Controller/Adminhtml/OAuth/CallbackTest.php
  AdobeIms/Test/Unit/Controller/Adminhtml/User/ProfileTest.php
  AdobeIms/Test/Unit/Observer/FlushUsersTokensObserverTest.php
  AdobeStockAsset/Test/Unit/Model/CategoryRepositoryTest.php
  AdobeStockAsset/Test/Unit/Model/CreatorRepositoryTest.php
  AdobeStockAsset/Test/Unit/Model/GetAssetByIdTest.php
  AdobeStockAsset/Test/Unit/Model/GetAssetListTest.php
  AdobeStockAsset/Test/Unit/Model/SaveAssetTest.php
  AdobeStockImage/Test/Unit/Model/GetImageListTest.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/ConfirmationTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/LicenseTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/License/QuotaTest.php
  AdobeStockImageAdminUi/Test/Unit/Controller/Adminhtml/Preview/DownloadTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/Block/Wysiwyg/Images/Content/Plugin/AddSearchButtonTest.php
  AdobeStockImageAdminUi/Test/Unit/Model/Listing/DataProviderTest.php
  AdobeStockImageAdminUi/Test/Unit/Ui/Component/Listing/Filter/ColorTest.php
  MediaGalleryUi/Test/Unit/Model/UploadImageTest.php
Labels: Partner: Mediotype, Progress: approved, partners-contribution

#1226 Improve media gallery styles && directory filters state
  AdobeStockImage/Model/Plugin/AddLicenseDataToAsset.php
  AdobeStockImage/composer.json
  AdobeStockImage/etc/di.xml
  AdobeStockImageAdminUi/Model/FilterParametersProvider/IsLicensed.php
  AdobeStockImageAdminUi/composer.json
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
  MediaGalleryUi/Model/FilterParametersProvider/Directory.php
  MediaGalleryUi/Model/FilterParametersProvider/Fulltext.php
  MediaGalleryUi/Model/Listing/DataProvider.php
  MediaGalleryUi/Model/SelectModifierComposite.php
  MediaGalleryUi/Model/SelectModifierInterface.php
  MediaGalleryUi/Ui/Component/Listing/Provider.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
Labels: Progress: ready for delivery

#1268 Batch delivery
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  MediaGalleryUi/Controller/Adminhtml/Directories/Delete.php
  MediaGalleryUi/Controller/Adminhtml/Image/Upload.php
  MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
  MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/sortBy.js
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Progress: ready for delivery, merge in progress

#1258 Frontend validation on uploading not supported file formats
  MediaGalleryUi/Controller/Adminhtml/Image/Upload.php
  MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
  MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Progress: ready for delivery

#1255 The Deleted folder reappears in Media Gallery after web page refresh
  MediaGalleryUi/Controller/Adminhtml/Directories/Delete.php
Labels: Progress: ready for delivery

#1253 Two identical error messages appear if try to License and Save an image without Client Secret key
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Progress: ready for delivery

#1230 Sorting options are incomplete
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/sortBy.js
Labels: Progress: ready for delivery

#1269 Apply bookmarks to save filters state and per page settings
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1274 Provide own insertAtcursor method to avoid mediaBrowser widget iniialization
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/insertImageAction.js
Labels: Progress: ready for delivery

#1267 Fix typos
  AdobeIms/Test/Unit/Model/GetAccessTokenTest.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
Labels: Cleanup, Progress: ready for delivery

#1275 Licensing frontend implementation refactoring
  AdobeStockAdminUi/view/adminhtml/templates/system/config/connection.phtml
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Model/SerializeImage.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImage/Test/Unit/Model/SerializeImageTest.php
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/confirmQuota.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/getLicenseStatus.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/licenseAndSave.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/save.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/saveLicensed.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/savePreview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/confirmation/buyCredits.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/confirmation/license.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/confirmation/save.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/confirmation/saveLicensed.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/path-utility.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/actions.html
  AdobeStockImageApi/Api/GetRelatedImagesInterface.php
  MediaGalleryUi/Model/Directories/FolderTree.php
  MediaGalleryUi/view/adminhtml/web/js/action/getDetails.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
  dev/tests/js/jasmine/tests/app/code/Magento/AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.test.js
Labels: Priority: P1, Progress: ready for delivery

#1263 Fixed issue with preview on image license
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImage/Model/SerializeImage.php
  AdobeStockImage/Test/Unit/Model/GetRelatedImagesTest.php
  AdobeStockImage/Test/Unit/Model/SerializeImageTest.php
  AdobeStockImage/etc/di.xml
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
  AdobeStockImageApi/Api/SerializeImageInterface.php
Labels: Progress: on hold

#1249 Correct license image procces to catch errors and show it on media gallery
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
Labels: Progress: on hold

#1288 Batch delivery
  MediaGallerySynchronization/Model/ResolveNonExistedAssets.php
  MediaGallerySynchronization/Model/Synchronize.php
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
Labels: Progress: ready for delivery

#1273 User is redirected to Media Gallery instead of staying on Image Details page (Delete confirmation message)
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
Labels: Priority: P2, Progress: ready for delivery

#1264 Media gallery synchronization does not remove obsolete images from database
  MediaGallerySynchronization/Model/ResolveNonExistedAssets.php
  MediaGallerySynchronization/Model/Synchronize.php
Labels: Priority: P1, Progress: ready for delivery

#1295 Added ability to locate node in jstree after create folder, and in bookmarks state
  MediaGalleryUi/Model/Directories/FolderTree.php
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Priority: P3, Progress: ready for delivery, Severity: S3

#1285 "Uploaded date" filter is missing from Media Gallery
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/sortBy.js
Labels: Progress: ready for delivery

#1284 View controls: Save all changes, Edit bookmark, Delete bookmark are shifted in Media Gallery
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: ready for delivery

#1282 Add color preview rectangle to Active filter state to color filter.
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/filter/chips.html
Labels: Priority: P3, Progress: ready for delivery

#1280 Fix used in section counts, with same image on one page
  MediaGalleryUi/Model/AssetDetailsProvider/UsedIn.php
  MediaGalleryUi/etc/di.xml
Labels: Priority: P1, Progress: ready for delivery, Section: Used In

#1279 1245: fix image still exists after delete
  MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
  MediaGalleryUi/Model/DeleteImage.php
Labels: Backend, Community Insider: Magecom, Priority: P1, Progress: ready for delivery, Severity: S1, community-insider-contribution, has dependency

#1259 "The image cannot be located" message appears if Save Preview when there are more than one page in Media Gallery
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/sortBy.js
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Priority: P2, Progress: ready for delivery

#1135 Integration tests for MediaGalleryIntegration module and unit test adjustments
  MediaGalleryIntegration/Test/Integration/Model/ImageComponentOpenDialogUrlTest.php
  MediaGalleryIntegration/Test/Integration/Model/OpenDialogUrlProviderTest.php
  MediaGalleryIntegration/Test/Integration/Model/TinyMceOpenDialogUrlTest.php
  MediaGalleryIntegration/Test/Integration/Model/WysiwygDefaultConfigOpenDialogUrlTest.php
Labels: Backend, Community Insider: Magecom, Event: Global-Contribution-Day, Priority: P3, Progress: ready for delivery, Severity: S3, community-insider-contribution

#1299 Image is not Opened in Media gallery if it is on another page in Media Gallery
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Priority: P2, Progress: ready for delivery
