Repository magento/adobe-stock-integration, pull requests merged in 2020-05, with the labels that each got.

#1251 Save content-asset association during the index process
  MediaContentSynchronization/Console/Command/Synchronize.php
  MediaContentSynchronization/LICENSE.txt
  MediaContentSynchronization/LICENSE_AFL.txt
  MediaContentSynchronization/Model/Synchronize.php
  MediaContentSynchronization/README.md
  MediaContentSynchronization/composer.json
  MediaContentSynchronization/etc/di.xml
  MediaContentSynchronization/etc/module.xml
  MediaContentSynchronization/modman
  MediaContentSynchronization/registration.php
  MediaContentSynchronizationApi/Api/SynchronizeInterface.php
  MediaContentSynchronizationApi/Api/SynchronizerInterface.php
  MediaContentSynchronizationApi/LICENSE.txt
  MediaContentSynchronizationApi/LICENSE_AFL.txt
  MediaContentSynchronizationApi/Model/SynchronizerPool.php
  MediaContentSynchronizationApi/README.md
  MediaContentSynchronizationApi/composer.json
  MediaContentSynchronizationApi/etc/module.xml
  MediaContentSynchronizationApi/modman
  MediaContentSynchronizationApi/registration.php
  MediaContentSynchronizationCatalog/LICENSE.txt
  MediaContentSynchronizationCatalog/LICENSE_AFL.txt
  MediaContentSynchronizationCatalog/Model/Synchronizer/Category.php
  MediaContentSynchronizationCatalog/Model/Synchronizer/Product.php
  MediaContentSynchronizationCatalog/README.md
  MediaContentSynchronizationCatalog/Test/Integration/Model/Synchronizer/CategoryTest.php
  MediaContentSynchronizationCatalog/Test/Integration/Model/Synchronizer/ProductTest.php
  MediaContentSynchronizationCatalog/composer.json
  MediaContentSynchronizationCatalog/etc/di.xml
  MediaContentSynchronizationCatalog/etc/module.xml
  MediaContentSynchronizationCatalog/modman
  MediaContentSynchronizationCatalog/registration.php
  MediaContentSynchronizationCms/LICENSE.txt
  MediaContentSynchronizationCms/LICENSE_AFL.txt
  MediaContentSynchronizationCms/Model/Synchronizer/Block.php
  MediaContentSynchronizationCms/Model/Synchronizer/Page.php
  MediaContentSynchronizationCms/README.md
  MediaContentSynchronizationCms/Test/Integration/Model/Synchronizer/BlockTest.php
  MediaContentSynchronizationCms/Test/Integration/Model/Synchronizer/PageTest.php
  MediaContentSynchronizationCms/composer.json
  MediaContentSynchronizationCms/etc/di.xml
  MediaContentSynchronizationCms/etc/module.xml
  MediaContentSynchronizationCms/modman
  MediaContentSynchronizationCms/registration.php
  modman
Labels: Priority: P1, Progress: approved

#1319 Fix "Search by keyword" doesn't find images in Media Gallery
  MediaGalleryUi/Model/FilterParametersProvider/Directory.php
  MediaGalleryUi/Model/FilterParametersProvider/Fulltext.php
  MediaGalleryUi/Ui/Component/DataProvider/KeywordFilter.php
  MediaGalleryUi/Ui/Component/Filters/Type/Search.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1315 Several fixes for Internet explorer & edge
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: ready for delivery

#1305 Internet explorer improvements && styles improvements
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: ready for delivery

#1323 fix typo. sentence in error message starts from lower case
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Frontend/UI, Progress: approved, good first issue

#1328 Fix styles for AdobeStok, IMprove AdobeStock Buttons to check configuration
  AdobeStockImageAdminUi/Ui/Component/Listing/SearchAdobeStockButton.php
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Priority: P1, Progress: review, Severity: S1

#1332 Fix Name && path sorting, fix Overlay label styles
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.js
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  dev/tests/js/jasmine/tests/app/code/Magento/AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.test.js
Labels: Award: bug fix, Progress: ready for delivery

#1348 [MFTF] Improve AdminLocalized test to be stable
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminAdobeStockKeywordLocalizedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminAdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
Labels: MFTF coverage, Progress: review

#1345 Fixed handling errors while licensing image from the media gallery
  AdobeStockImageAdminUi/view/adminhtml/web/js/action/saveLicensed.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
  MediaGalleryUi/view/adminhtml/templates/image_details.phtml
  MediaGalleryUi/view/adminhtml/templates/image_details_standalone.phtml
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
Labels: Progress: ready for delivery

#1364 Added MediaContent modules to metapackage
  _metapackage/composer.json
Labels: Progress: approved

#1354 Improve the Sort by name text in drop-down
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Frontend/UI, Priority: P2, Progress: approved

#1351 Improve the delete success message
  MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
Labels: Frontend/UI, Priority: P2, Progress: approved

#1357 Fix image Preview is not closed when Sort by is changed in Adobe Stoc…
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
Labels: Priority: P3, Progress: review

#1349 Issue #1343 - Fixed bug with filter and bookmarks
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/related.js
Labels: Award: bug fix, Priority: P2, Progress: approved, Severity: S2

#1369 Skip ImsSigned suite
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSaveLicensedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSavedLicensedImageLocateTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignedInCreditsVisibleTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminViewsStockLicenseStatusTest.xml
Labels: Progress: approved

#1329 [MFTF] Media Gallery View Details tests
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockExpandImagePreviewActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockVerifyImageDetailsActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGallerySearchAdobeStockActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockImageData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminAdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminEnhancedMediaGalleryActionsSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminEnhancedMediaGalleryImageActionsSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminEnhancedMediaGalleryViewDetailsSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/AdobeStockMediaGallerySuite.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryViewAdobeStockDetailsTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/template/mediaGallery/grid/columns/image/licenseActions.html
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryImageDetailsDeleteActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryUploadImageActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyImageDetailsActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryViewImageDetailsActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryActionsSection.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryImageActionsSection.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryViewDetailsSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryCreateDeleteFolderTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryCreateDeleteFolderTest.xml
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
Labels: Priority: P1, Progress: review

#1188 AdobeStockAsset integration tests
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/GetAssetById.php
  AdobeStockAsset/Model/ResourceModel/Category/Command/LoadById.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/LoadById.php
  AdobeStockAsset/Test/Integration/Model/AssetRepositoryTest.php
  AdobeStockAsset/Test/Integration/Model/CategoryRepositoryTest.php
  AdobeStockAsset/Test/Integration/Model/CreatorRepositoryTest.php
  AdobeStockAsset/Test/Integration/Model/SaveAssetTest.php
  AdobeStockAsset/Test/_files/asset.php
  AdobeStockAsset/Test/_files/asset_rollback.php
  AdobeStockAsset/Test/_files/category.php
  AdobeStockAsset/Test/_files/category_rollback.php
  AdobeStockAsset/Test/_files/creator.php
  AdobeStockAsset/Test/_files/creator_rollback.php
  AdobeStockAsset/Test/_files/media_asset.php
  AdobeStockAsset/Test/_files/media_asset_rollback.php
  AdobeStockAssetApi/Model/Asset/Command/LoadByIdInterface.php
Labels: Asset Component, Backend, Community Insider: Magecom, Priority: P3, Progress: changes requested, community-insider-contribution

#1366 Fix "Image cannot be located" message appears if try to Save Preview …
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Progress: ready for delivery

#1371 Remove duplicated uploaded date filter
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1375 User resource connetion, to cover case with table prefix
  AdobeStockImageAdminUi/Model/FilterParametersProvider/IsLicensed.php
Labels: Progress: acceptance testing

#1334 [MFTF] Media Gallery grid attributes tests
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockOpenFromEnhancedMediaGalleryActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminSaveAdobeStockLicensedImageActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminAdobeStockImageUnlicensedLabelActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Data/AdobeStockImageData.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminAdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminEnhancedMediaGalleryImageSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/AdobeStockMediaGalleryImsSignedSuite.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLicensedImageViewLabelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockNotLicensedImageLicenseTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSaveLicenseWithSavedPreviewTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInSignOutTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockTryLicenseAlreadyLicensedImageTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockVerifyLicensedLabelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockVerifyUnlicensedLabelTest.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryImageDeleteActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AssertImageAttributesOnEnhancedMediaGalleryActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryDeleteModalSection.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryImageDescriptionSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryVerifyImageGridAttributesTest.xml
Labels: MFTF coverage, Progress: review

#1365 Issue: 1361 - Fixed issue with folders with same name.
  AdobeStockImageAdminUi/view/adminhtml/web/js/media-gallery.js
Labels: Award: bug fix, Progress: ready for delivery, Severity: S2

#1377 Asi fix resource connection to support table-prefix
  MediaGalleryUi/Ui/Component/DataProvider/KeywordFilter.php
Labels: Progress: approved

#1355 Set property when component initialized
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Priority: P1, Progress: ready for delivery

#1360 [MFTF] Cover adding Category image via WYSIWYG from Enhanced Media Gallery
  AdobeStockImageAdminUi/view/adminhtml/web/template/mediaGallery/grid/columns/image/licenseActions.html
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryClickAddSelectedActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryClickImageInGridActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryClickOkButtonTinyMce4ActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminOpenMediaGalleryFromTinyMce4IconActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/StoreFrontMediaGalleryAssertImageInCategoryDescriptionActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryImageActionsSection.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryViewDetailsSection.xml
  MediaGalleryUi/Test/Mftf/Section/AdminMediaGalleryHeaderButtonsSection.xml
  MediaGalleryUi/Test/Mftf/Suite/MediaGalleryUiSuite.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryAddCategoryImageTest.xml
Labels: MFTF coverage, Priority: P2, Progress: approved

#1376 MQE-2113: fix errors reported by the annotation static check
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryCreateDeleteFolderTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryCreateDeleteFolderTest.xml
Labels: Progress: approved

#1367 1336: async run image files and content synchronization
  MediaContentSynchronization/Model/Consume.php
  MediaContentSynchronization/Model/Publish.php
  MediaContentSynchronization/Plugin/SynchronizeMediaContent.php
  MediaContentSynchronization/composer.json
  MediaContentSynchronization/etc/communication.xml
  MediaContentSynchronization/etc/di.xml
  MediaContentSynchronization/etc/queue_consumer.xml
  MediaContentSynchronization/etc/queue_publisher.xml
  MediaContentSynchronization/etc/queue_topology.xml
  MediaGallerySynchronization/Model/Consume.php
  MediaGallerySynchronization/Model/Publish.php
  MediaGallerySynchronization/Plugin/MediaGallerySyncTrigger.php
  MediaGallerySynchronization/composer.json
  MediaGallerySynchronization/etc/communication.xml
  MediaGallerySynchronization/etc/queue_consumer.xml
  MediaGallerySynchronization/etc/queue_publisher.xml
  MediaGallerySynchronization/etc/queue_topology.xml
Labels: Backend, Community Insider: Magecom, Progress: changes requested, community-insider-contribution

#1388 [MFTF]Added stories and testCaseId
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryVerifyImageGridAttributesTest.xml
Labels: Progress: approved

#1383 [TR]: MySQL8 Support
  AdobeIms/etc/db_schema.xml
  AdobeStockAsset/etc/db_schema.xml
Labels: Partner: TechDivision, Progress: approved, partners-contribution

#1379 [MFTF] Added delete image from context menu test
  MediaGalleryUi/Test/Mftf/ActionGroup/AssertEnhancedMediaGalleryImageDeletedActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryImageActionsSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageContextMenuTest.xml
Labels: Progress: review

#1381 [MFTF] Added test o add image from image details
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryAddImageFromImageDetailsActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AssertImageAddedToPageContentActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryViewDetailsSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryAddFromImageDetailsTest.xml
Labels: Progress: approved

#1350 Respect (current_tree_path parameter) on opening media gallery
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: ready for delivery
