Repository magento/adobe-stock-integration, pull requests merged in 2020-09, with the labels that each got.

#1756 #1504: [2.1-develop] Insert rendition images to the content from media gallery instead of original images
  MediaGalleryRenditions/Plugin/SetRenditionPath.php
  MediaGalleryRenditions/Test/Integration/Model/ExtractAssetsFromContentWithRenditionTest.php
  MediaGalleryRenditions/composer.json
  MediaGalleryRenditions/etc/di.xml
  MediaGalleryRenditions/etc/media_content.xml
Labels: Priority: P2, Progress: ready for delivery, Severity: S2, has dependency

#1811 Locate functionality fix and ACL renaming
  AdobeStockAsset/etc/acl.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Priority: P2, Severity: S2

#1812 #1809: Long image name doesn't fit into License "Adobe Stock Images...?" message
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: ready for delivery

#1819 [2.1.0-master] Unskipped AdminMediaGalleryPageSavedPreviewAddSelectedTest
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryPageSavedPreviewAddSelectedTest.xml
Labels: Priority: P2, Severity: S2

#1803 Cover GetAssetListInterface with an integration test
  AdobeStockAsset/Test/Integration/Model/ClientMock.php
  AdobeStockAsset/Test/Integration/Model/GetAssetListTest.php
Labels: Priority: P3, Progress: changes requested

#1826 [WIP] #1802: The "three dots" context menu is not closed after unsuccessful licensing from Media Gallery
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryUnsuccessfulLicensingTest.xml
Labels: Progress: changes requested

#1828 #1823: Cover GetAssetByIdInterface with integration test
  AdobeStockAsset/Test/Integration/Model/ClientMock.php
  AdobeStockAsset/Test/Integration/Model/GetAssetByIdTest.php
  AdobeStockAsset/Test/Integration/Model/GetAssetListTest.php
Labels: Progress: changes requested

#1831 #1786 :- Replace DocumentToAssetTest unit test with an integration test
  AdobeStockImage/Test/Integration/Model/Extract/DocumentToAssetTest.php
  AdobeStockImage/Test/Unit/Model/Extract/DocumentToAssetTest.php
Labels: Award: test coverage, Progress: changes requested

#1836 Cover SaveImageInterface with integration test
  AdobeStockImage/Test/Integration/Model/HttpsDriverMock.php
  AdobeStockImage/Test/Integration/Model/SaveImageTest.php
  AdobeStockImage/Test/Integration/_files/magento-logo.png
Labels: Priority: P3, Progress: changes requested, Severity: S3

#1835 AdminAdobeStockInsertRenditionImageFromGalleryFileSizeTest
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockInsertRenditionImageFromGalleryFileSizeTest.xml
Labels: Priority: P3, Progress: ready for delivery, Severity: S3

#1847 Fix error when saving image from stock that does not have Category
  AdobeStockAsset/Model/Asset.php
  AdobeStockAsset/Model/SaveAsset.php
  AdobeStockAsset/Test/Integration/Model/SaveAssetTest.php
  AdobeStockImageAdminUi/Plugin/AddAdobeStockImageDetailsPlugin.php
Labels: Progress: ready for delivery
