Repository magento/adobe-stock-integration, pull requests merged in 2020-01, with the labels that each got.

#878 Render image details for media gallery grid
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/Ui/Component/Listing/Columns/Url.php
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/images/Astock.png
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
Labels: Progress: changes requested

#854 733: provide commands for the adobe stock asset
  AdobeStockAsset/Model/AppendAttributes.php
  AdobeStockAsset/Model/AssetRepository.php
  AdobeStockAsset/Model/CategoryRepository.php
  AdobeStockAsset/Model/CreatorRepository.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/DeleteById.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/LoadById.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/LoadByIds.php
  AdobeStockAsset/Model/ResourceModel/Asset/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Category/Command/DeleteById.php
  AdobeStockAsset/Model/ResourceModel/Category/Command/LoadById.php
  AdobeStockAsset/Model/ResourceModel/Category/Command/Save.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/DeleteById.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/LoadById.php
  AdobeStockAsset/Model/ResourceModel/Creator/Command/Save.php
  AdobeStockAsset/Test/Unit/Model/CategoryRepositoryTest.php
  AdobeStockAsset/Test/Unit/Model/CreatorRepositoryTest.php
  AdobeStockAsset/etc/di.xml
  AdobeStockAssetApi/Api/AssetRepositoryInterface.php
  AdobeStockAssetApi/Model/Asset/Command/DeleteByIdInterface.php
  AdobeStockAssetApi/Model/Asset/Command/LoadByIdInterface.php
  AdobeStockAssetApi/Model/Asset/Command/LoadByIdsInterface.php
  AdobeStockAssetApi/Model/Asset/Command/SaveInterface.php
  AdobeStockAssetApi/Model/Category/Command/DeleteByIdInterface.php
  AdobeStockAssetApi/Model/Category/Command/LoadByIdInterface.php
  AdobeStockAssetApi/Model/Category/Command/SaveInterface.php
  AdobeStockAssetApi/Model/Creator/Command/DeleteByIdInterface.php
  AdobeStockAssetApi/Model/Creator/Command/LoadByIdInterface.php
  AdobeStockAssetApi/Model/Creator/Command/SaveInterface.php
  MediaGalleryUi/Model/ImagesIndexer.php
  MediaGalleryUi/Test/Unit/Model/Filesystem/ImagesProviderTest.php
  MediaGalleryUi/composer.json
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/view/adminhtml/layout/media_gallery_index_index.xml
Labels: Asset Component, Award: advanced, Award: category of expertise, Backend, Community Insider: Magecom, Progress: review, community-insider-contribution, enhancement

#855 Quantity of images is not updated after image was licensed && License and Save popup must be closed after confirm click immediately
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Progress: changes requested

#886 Updating Slack link in README
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockImsPopupClickSignInActionGroup.xml
  README.md
  dev/travis/after_failure.sh
Labels: Progress: review

#887 Do not show name confirmation for licensing image with saved preview
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockSaveLicensedActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockImagePreviewSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSaveLicenseWithSavedPreviewTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Partner: Atwix, Progress: approved, partners-contribution

#892 Add "Unlicensed" overlay to media gallery grid
  AdobeStockImage/Model/AssetIndexer.php
  AdobeStockImage/Test/Unit/Model/AssetIndexerTest.php
  AdobeStockImage/composer.json
  AdobeStockImage/etc/db_schema.xml
  AdobeStockImage/etc/db_schema_whitelist.json
  AdobeStockImage/etc/di.xml
  AdobeStockImage/etc/module.xml
  MediaGalleryUi/Console/Command/IndexAssets.php
  MediaGalleryUi/Model/AssetIndexer.php
  MediaGalleryUi/Model/ImagesIndexer.php
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/Ui/Component/Listing/Columns/UnlicensedOverlay.php
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUiApi/Api/ImagesIndexerInterface.php
Labels: Progress: changes requested

#899 Moved media gallery to the slide panel
  AdobeStockAdminUi/Test/Mftf/Section/AdminConfigSystemSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-configuration.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-filters.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-grid.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-ims.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-keywords.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-license.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-preview.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration-see-more.xml
  AdobeStockImageAdminUi/Test/Mftf/Suite/adobe-stock-integration.xml
  MediaGalleryUi/Controller/Adminhtml/Index/Index.php
  MediaGalleryUi/Plugin/UpdateOpenDialogUrl.php
  MediaGalleryUi/Plugin/UpdateWysiwygOpenDialogUrl.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryEnhancedEnableActionGroup.xml
  MediaGalleryUi/Test/Mftf/Data/AdobeStockConfigData.xml
  MediaGalleryUi/Test/Mftf/Section/AdminConfigSystemSection.xml
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/etc/adminhtml/menu.xml
  MediaGalleryUi/view/adminhtml/layout/media_gallery_index_index.xml
  MediaGalleryUi/view/adminhtml/templates/container.phtml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/container.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
Labels: Progress: review

#885 #798 : Cover overlay.js with jasmine tests
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  dev/tests/js/jasmine/tests/app/code/Magento/AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/overlay.test.js
Labels: Progress: approved

#897 [WIP] #828 : Update media gallery grid styles to match the mockups
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: approved
