Repository magento/adobe-stock-integration, pull requests merged in 2020-02, with the labels that each got.

#946 Added ru_RU locale deployment command for functional tests
  dev/travis/before_script.sh
Labels: Partner: Atwix, Progress: approved, partners-contribution

#944 Remove redundant field key from IMS UserRepository::get method
  AdobeIms/Model/UserProfileRepository.php
Labels: Partner: Monsoon, Progress: approved, partners-contribution

#943 Added license status filter to Media Gallery
  AdobeStockImage/Ui/Options/Licensed.php
  AdobeStockImage/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Event: mm20in, Partner: Zilker Technology, Progress: approved, partners-contribution

#941 Fixed failing localized image preview keyword assertion
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AssertAdminAdobeStockImageKeywordActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockLocalizationTest.xml
Labels: Partner: Atwix, Progress: approved, partners-contribution

#948 Improve AdobeIms/Test/Unit/Block/Adminhtml/SignInTest.php
  AdobeIms/Test/Unit/Block/Adminhtml/SignInTest.php
Labels: Partner: Monsoon, Progress: review, partners-contribution

#952 FIX: clean up
  AdobeStockImage/Model/Storage/Delete.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImageAdminUi/Plugin/AddSearchButton.php
Labels: Community Insider: Magecom, Progress: approved, community-insider-contribution

#953 Refactoring changes
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Licensed/Options.php
  AdobeStockImageAdminUi/composer.json
  AdobeStockImageAdminUi/etc/module.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Progress: approved

#950 Added cancel button to Media Gallery
  MediaGalleryUi/view/adminhtml/layout/media_gallery_index_index.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Partner: Zilker Technology, Progress: changes requested, partners-contribution

#931 Created constants for string values used in the code
  AdobeIms/Block/Adminhtml/SignIn.php
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Model/Config.php
  AdobeIms/Model/ResourceModel/UserProfile.php
  AdobeStockAdminUi/Block/Adminhtml/System/Config/TestConnection.php
  AdobeStockClient/Model/Client/Files.php
  AdobeStockClient/Model/SearchParametersProvider/ContentType.php
  AdobeStockClient/Model/SearchParametersProvider/Isolated.php
  AdobeStockClient/Model/SearchParametersProvider/MediaId.php
  AdobeStockClient/Model/SearchParametersProvider/Offensive.php
  AdobeStockClient/Model/SearchParametersProvider/Orientation.php
  AdobeStockClient/Model/SearchParametersProvider/Similar.php
  AdobeStockClient/Model/StockFileToDocument.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/RelatedImages.php
Labels: Cleanup, Partner: Krish TechnoLabs, Progress: changes requested, partners-contribution

#956 Added observer to role update and updated/created unit tests
  AdobeIms/Model/FlushUserTokens.php
  AdobeIms/Observer/FlushUsersTokensObserver.php
  AdobeIms/Test/Unit/Model/FlushUserTokensTest.php
  AdobeIms/Test/Unit/Observer/FlushUsersTokensObserverTest.php
  AdobeIms/etc/adminhtml/events.xml
Labels: Award: bug fix, Award: test coverage

#940 Fix the Adobe Stock asset source icon url set by indexer
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/UnlicensedOverlay.php
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/Console/Command/IndexAssets.php
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/Plugin/UpdateAssetInGrid.php
  MediaGalleryUi/Ui/Component/Listing/Columns/SourceIconProvider.php
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/container.js
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
Labels: Award: bug fix, Backend, Community Insider: Magecom, Progress: changes requested, community-insider-contribution

#942 905: searh by keyword filter
  MediaGalleryUi/Model/UpdateAssetKeywordsInGrid.php
  MediaGalleryUi/Plugin/UpdateAssetKeywordsInGrid.php
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
Labels: Backend, Community Insider: Magecom, Progress: changes requested, community-insider-contribution

#951 Added PHPUnit test for AdobeIms/Model/Config
  AdobeIms/Model/Config.php
  AdobeIms/Test/Unit/Model/ConfigTest.php
Labels: Award: test coverage, Partner: Zilker Technology, Progress: changes requested, partners-contribution

#936 Display folders filter as a directory tree
  MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
  MediaGalleryUi/Model/Directories/FolderTree.php
  MediaGalleryUi/Ui/Component/DirectoriesTree.php
  MediaGalleryUi/Ui/Options/Directory.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/images/d.png
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
  MediaGalleryUi/view/adminhtml/web/template/grid/directories/directoryTree.html
Labels: Award: advanced, Progress: review

#945 Handle DB Storage and thumbnails when deleting a preview image
  AdobeStockImage/Model/Storage/Delete.php
  AdobeStockImage/Test/Unit/Model/Storage/DeleteTest.php
  AdobeStockImage/composer.json
Labels: Progress: changes requested

#947 Set unlicensed overlay for saved Adobe Stock image preview without reindex
  AdobeStockImage/Model/AssetIndexer.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SetLicensedInMediaGalleryGrid.php
  AdobeStockImage/Test/Unit/Model/AssetIndexerTest.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/SetLicensedInMediaGalleryGridTest.php
  AdobeStockImage/etc/di.xml
Labels: Award: test coverage, Progress: changes requested

#949 Make UserProfile interface nullable, cover implementation with unit test
  AdobeIms/Model/UserProfile.php
  AdobeIms/Test/Unit/Model/UserProfileTest.php
  AdobeImsApi/Api/Data/UserProfileInterface.php
Labels: Award: test coverage, Partner: Monsoon, Progress: changes requested, partners-contribution

#884 [MFTF] Message disappear when the request with broken credentials is sent second time
  AdobeStockAdminUi/Test/Mftf/Test/AdminCannotAccessStockImagesWithWrongCredentialsTest.xml
Labels: Award: MFTF test coverage, Progress: review

#969 Added keyword population to media-gallery:index
  MediaGalleryUi/Model/UpdateAssetInGrid.php
Labels: Partner: Zilker Technology, partners-contribution

#975 Fixed code sniffer issue
  MediaGalleryUi/Console/Command/IndexAssets.php
  MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
  MediaGalleryUi/Controller/Adminhtml/Index/Index.php
  MediaGalleryUi/Model/ImagesIndexer.php
  MediaGalleryUi/Model/UpdateAssetInGrid.php
  MediaGalleryUi/Plugin/UpdateAssetKeywordsInGrid.php
  MediaGalleryUi/Plugin/UpdateOpenDialogUrl.php
  MediaGalleryUi/Plugin/UpdateWysiwygOpenDialogUrl.php
  dev/travis/script.sh
Labels: Progress: approved

#977 #865 : Possible to open several "Sign In Adobe ID" windows
  AdobeIms/view/adminhtml/web/js/action/authorization.js
Labels: Award: bug fix, Progress: approved

#968 Added check for Adobe sign in button visibility
  AdobeStockImageAdminUi/Test/Mftf/Section/AdobeStockSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockSignInACLTest.xml
  AdobeStockImageAdminUi/view/adminhtml/layout/cms_wysiwyg_images_index.xml
Labels: Award: MFTF test coverage, Award: bug fix, Partner: Zilker Technology, partners-contribution

#970 #issue-902 Added functionality to delete an image from media gallery
  AdobeStockImageAdminUi/view/adminhtml/ui_component/adobe_stock_images_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
  MediaGalleryUi/Model/DeleteImageByAssetId.php
  MediaGalleryUi/etc/db_schema.xml
  MediaGalleryUi/etc/db_schema_whitelist.json
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/grid/messages.js
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image/actions.html
  MediaGalleryUi/view/adminhtml/web/template/grid/messages.html
Labels: Award: advanced, Partner: Atwix, partners-contribution

#976 Implement HTTP action interface in controllers
  AdobeIms/Controller/Adminhtml/OAuth/Callback.php
  AdobeIms/Controller/Adminhtml/User/Logout.php
  AdobeIms/Controller/Adminhtml/User/Profile.php
  AdobeIms/view/adminhtml/web/js/signIn.js
  AdobeStockAdminUi/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAdminUi/view/adminhtml/web/js/connection.js
  AdobeStockImageAdminUi/Controller/Adminhtml/License/Confirmation.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetList.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/License.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/Quota.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/SaveLicensed.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/Download.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/RelatedImages.php
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
  MediaGalleryUi/Controller/Adminhtml/Directories/GetTree.php
  MediaGalleryUi/Controller/Adminhtml/Index/Index.php
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: changes requested
