Repository magento/adobe-stock-integration, pull requests merged in 2020-08, with the labels that each got.

#1655 1618: Duplicated Items in Used in Entities filters
  MediaGalleryCatalogUi/view/adminhtml/ui_component/media_gallery_category_listing.xml
  MediaGalleryCatalogUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryCatalogUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryCmsUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryCmsUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1674 Redirect to "Adobe Stock Integration" config path more accurate
  AdobeStockAsset/Model/GetAssetList.php
Labels: Progress: ready for delivery, Technology Partner: Magestore, tech-partners-contribution

#1683 #1600: Improvements to mass delete message
  MediaGalleryUi/Controller/Adminhtml/Image/Delete.php
Labels: Progress: changes requested

#1685 #1667: Add a column with an edit link to the Category grid
  MediaGalleryCatalogUi/Ui/Component/Listing/Columns/CategoryActions.php
  MediaGalleryCatalogUi/view/adminhtml/ui_component/media_gallery_category_listing.xml
Labels: Progress: review

#1678 1641: The loop symbol overlaps the text in Used in Products filter [Device mod]
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: acceptance testing

#1682 Fix Delete Images... on click event binding after cloning element
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryDisableMassactionModeActionGroup.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryDeleteImagesInBulkTest.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactionView.js
Labels: MFTF coverage

#1675 Add support of PNG IPTC reading && writing to MediaGalleryMetadata module implementation
  MediaGalleryMetadata/Model/Png/Segment/ReadIptc.php
  MediaGalleryMetadata/Model/Png/Segment/WriteIptc.php
  MediaGalleryMetadata/Test/Integration/Model/AddMetadataTest.php
  MediaGalleryMetadata/Test/Integration/Model/ExtractMetadataTest.php
  MediaGalleryMetadata/Test/Integration/Model/Png/Segment/IptcTest.php
  MediaGalleryMetadata/Test/_files/empty_iptc.png
  MediaGalleryMetadata/Test/_files/iptc_only.png
  MediaGalleryMetadata/etc/di.xml
  MediaGalleryUi/Test/Mftf/Data/AdminEnhancedMediaGalleryImageData.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryUploadImageWithMetadataTest.xml
Labels: MFTF coverage, Progress: acceptance testing

#1634 #1612: [Refactoring] Templates
  AdobeStockAdminUi/view/adminhtml/web/template/connection.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/image-preview.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/actions.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/keywords.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/column/preview/related.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/grid/filter/chips.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/image/adobe-stock-image-details.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/mediaGallery/grid/columns/image/licenseActions.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/signIn.html
  AdobeStockImageAdminUi/view/adminhtml/web/template/sorting.html
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image.html
  MediaGalleryUi/view/adminhtml/web/template/grid/columns/image/actions.html
  MediaGalleryUi/view/adminhtml/web/template/grid/filters/elements/ui-select.html
  MediaGalleryUi/view/adminhtml/web/template/grid/massactions/count.html
  MediaGalleryUi/view/adminhtml/web/template/image-uploader.html
  MediaGalleryUi/view/adminhtml/web/template/image/actions.html
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Priority: P1, Progress: ready for delivery, Severity: S2

#1636 [Refactoring] Refactor js Components && SQL Optimization
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/validation/validate-image-name.js
  MediaGalleryCatalogUi/etc/adminhtml/di.xml
  MediaGalleryCmsUi/etc/adminhtml/di.xml
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Duplicated.php
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/EntityType.php
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Keyword.php
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageWithWarningPopupTest.xml
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImages.js
  MediaGalleryUi/view/adminhtml/web/js/action/getDetails.js
  MediaGalleryUi/view/adminhtml/web/js/action/saveDetails.js
  MediaGalleryUi/view/adminhtml/web/js/directory/actions/createDirectory.js
  MediaGalleryUi/view/adminhtml/web/js/directory/actions/deleteDirectory.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directories.js
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/actions.js
  MediaGalleryUi/view/adminhtml/web/js/grid/columns/image/insertImageAction.js
  MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactionView.js
  MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactions.js
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js
  MediaGalleryUi/view/adminhtml/web/template/grid/massactions/cancelButton.html
Labels: Priority: P1, Progress: ready for delivery, Severity: S2

#1689 Use ImportFileComposite in Adobe Stock
  AdobeStockImage/Model/Extract/MediaGalleryAsset.php
  AdobeStockImage/Model/SaveImage.php
  AdobeStockImage/Model/SaveKeywords.php
  AdobeStockImage/Model/SaveMediaGalleryAsset.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/SaveImageFileTest.php
  AdobeStockImage/Test/Unit/Model/SaveImageTest.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
  AdobeStockImage/composer.json
  AdobeStockImageApi/Api/SaveImageInterface.php
  MediaGalleryIntegration/Plugin/SaveBaseCategoryImageInformation.php
  MediaGalleryIntegration/Plugin/SaveImageInformation.php
  MediaGallerySynchronization/Model/FetchMediaStorageFileBatches.php
  MediaGallerySynchronization/Model/ImportImageFileKeywords.php
  MediaGallerySynchronization/Model/ImportMediaAsset.php
  MediaGallerySynchronization/Model/SynchronizeFiles.php
  MediaGallerySynchronization/Test/Integration/Model/GetContentHashTest.php
  MediaGallerySynchronization/etc/di.xml
  MediaGallerySynchronizationApi/Api/SynchronizeFilesInterface.php
  MediaGallerySynchronizationApi/Model/ImportFilesComposite.php
  MediaGallerySynchronizationApi/Model/ImportFilesInterface.php
  MediaGallerySynchronizationApi/etc/di.xml
  MediaGalleryUi/Plugin/CreateThumbnails.php
  MediaGalleryUi/Plugin/ResizeSyncedFiles.php
  MediaGalleryUi/etc/di.xml
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Progress: ready for delivery

#1605 #1515: Add keywords field to the edit image description slide panel
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyImageKeywordsActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryEditAssetAddKeywordActionGroup.xml
  MediaGalleryUi/Test/Mftf/Data/AdminEnhancedMediaGalleryImageData.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryEditDetailsSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewDetailsEditTest.xml
  MediaGalleryUi/view/adminhtml/templates/image_edit_details.phtml
  MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
  MediaGalleryUi/view/adminhtml/web/js/action/saveDetails.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js
  MediaGalleryUi/view/adminhtml/web/js/validation/validate-image-keyword.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Priority: P1, Progress: ready for delivery, Severity: S1

#1681 #1503 :- Add links to grids to the image details panel
  MediaGalleryCatalogUi/etc/adminhtml/di.xml
  MediaGalleryCmsUi/etc/adminhtml/di.xml
  MediaGalleryUi/Model/AssetDetailsProvider/UsedIn.php
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageWithWarningPopupTest.xml
  MediaGalleryUi/Ui/Component/Listing/Filters/Asset.php
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
Labels: Priority: P1, Progress: ready for delivery, Severity: S1

#1737 fix Used in entity is removed after and Image Preview has been Licensed
  AdobeStockImage/Model/SaveImageFile.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/SaveImageFileTest.php
Labels: Priority: P1, Progress: ready for delivery, Severity: S1

#1741 Added CSP policy
  AdobeStockImageAdminUi/etc/csp_whitelist.xml
Labels: Priority: P2, Progress: ready for delivery, Severity: S3

#1734 Remove Source filter
  AdobeStockImageAdminUi/Plugin/AddAdobeStockSourceOptionPlugin.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Source/Options.php
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Priority: P1, Progress: ready for delivery, Severity: S1

#1715 #1688: Saved image from Adobe Stock is selected/highlighted, but the "Add Selected" button is not displayed
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryCategorySavedPreviewAddSelectedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryPageSavedPreviewAddSelectedTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Priority: P3, Progress: ready for delivery

#1720 Open in Media Gallery button doesn't search for the image if the Title has been Edited
  AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetMediaGalleryAsset.php
  AdobeStockImageAdminUi/Model/Asset/GetMediaGalleryAssetByAdobeId.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/composer.json
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Priority: P2, Progress: ready for delivery, Severity: S3

#1745 Sync 2.0-master with 2.0-develop
  AdobeStockImage/Model/SaveImageFile.php
  AdobeStockImage/Model/Storage/Save.php
  AdobeStockImage/Test/Unit/Model/SaveImageFileTest.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetMediaGalleryAsset.php
  AdobeStockImageAdminUi/Model/Asset/GetMediaGalleryAssetByAdobeId.php
  AdobeStockImageAdminUi/Plugin/AddAdobeStockSourceOptionPlugin.php
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryCategorySavedPreviewAddSelectedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryPageSavedPreviewAddSelectedTest.xml
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/ImagePreview.php
  AdobeStockImageAdminUi/Ui/Component/Listing/Columns/Source/Options.php
  AdobeStockImageAdminUi/composer.json
  AdobeStockImageAdminUi/etc/adminhtml/di.xml
  AdobeStockImageAdminUi/etc/csp_whitelist.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/image-preview.js
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
  MediaGalleryRenditions/LICENSE.txt
  MediaGalleryRenditions/LICENSE_AFL.txt
  MediaGalleryRenditions/README.md
  MediaGalleryRenditions/composer.json
  MediaGalleryRenditions/etc/adminhtml/system.xml
  MediaGalleryRenditions/etc/config.xml
  MediaGalleryRenditions/etc/module.xml
  MediaGalleryRenditions/modman
  MediaGalleryRenditions/registration.php
  MediaGalleryRenditionsApi/LICENSE.txt
  MediaGalleryRenditionsApi/LICENSE_AFL.txt
  MediaGalleryRenditionsApi/Model/Config.php
  MediaGalleryRenditionsApi/README.md
  MediaGalleryRenditionsApi/composer.json
  MediaGalleryRenditionsApi/etc/module.xml
  MediaGalleryRenditionsApi/modman
  MediaGalleryRenditionsApi/registration.php
  _metapackage/composer.json
Labels: 2.4-develop: :four:

#1507 #1476 :- Generate renditions for all images uploaded to magento
  MediaGalleryRenditions/Model/Config.php
  MediaGalleryRenditions/Model/GenerateRenditions.php
  MediaGalleryRenditions/Model/GetRenditionPath.php
  MediaGalleryRenditions/Model/IsRenditionRequired.php
  MediaGalleryRenditions/Plugin/CreateRenditions.php
  MediaGalleryRenditions/composer.json
  MediaGalleryRenditions/etc/di.xml
  MediaGalleryRenditions/etc/module.xml
  MediaGalleryRenditionsApi/Api/GenerateRenditionsInterface.php
  MediaGalleryRenditionsApi/Api/GetRenditionPathInterface.php
  MediaGalleryRenditionsApi/etc/module.xml
Labels: Award: complex, Progress: ready for delivery

#1753 CSP for profile image
  AdobeStockImageAdminUi/etc/csp_whitelist.xml
Labels: Progress: acceptance testing

#1757 Added missing MediaGalleryRendition extension in composer
  _metapackage/composer.json
Labels: Progress: acceptance testing

#1761 Removed unused class
  AdobeStockImage/Model/Storage/Delete.php
  AdobeStockImage/Test/Unit/Model/Storage/DeleteTest.php
  AdobeStockImage/composer.json
Labels: Progress: acceptance testing

#1772 Refactor image location on Save Preview && License image
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockMediaGalleryClearFiltersActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/ActionGroup/AdminAdobeStockMediaGallerySearchByKeywordActionGroup.xml
  AdobeStockImageAdminUi/Test/Mftf/Section/AdminEnhancedMediaGalleryActionsSection.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockImageVerifyLicenseActionOnMediaGallery.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockTryLicenseAlreadyLicensedImageTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockVerifyUnlicensedLabelTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryCategorySavedPreviewAddSelectedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryPageSavedPreviewAddSelectedTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryViewAdobeStockDetailsTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGallerySearchByKeywordTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewAdobeStockDetailsTest.xml
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Priority: P2, Progress: ready for delivery, Severity: S1

#1762 Integration test coverage for rendition image generation
  MediaGalleryRenditions/Test/Integration/Model/GenerateRenditionsTest.php
  MediaGalleryRenditions/Test/Integration/Model/GetRenditionPathTest.php
  MediaGalleryRenditions/Test/_files/magento_large_image.jpg
  MediaGalleryRenditions/Test/_files/magento_medium_image.jpg
Labels: Award: category of expertise, Priority: P3, Progress: acceptance testing, Severity: S2

#1777 Update is_downloaded for displayed record that was applied from related or series tab
  AdobeStockImageAdminUi/Controller/Adminhtml/Asset/GetMediaGalleryAsset.php
  AdobeStockImageAdminUi/Model/Asset/GetMediaGalleryAssetByAdobeId.php
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
  AdobeStockImageAdminUi/view/adminhtml/web/js/components/grid/column/preview/actions.js
Labels: Priority: P2, Progress: acceptance testing, Severity: S1

#1781 [Refactoring] Model view responsibility separation
  AdobeStockAdminUi/Controller/Adminhtml/System/Config/TestConnection.php
  AdobeStockAdminUi/view/adminhtml/web/js/connection.js
  AdobeStockAsset/Model/GetAssetById.php
  AdobeStockAsset/Model/GetAssetList.php
  AdobeStockImage/Model/GetRelatedImages.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/License.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/SaveLicensed.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/Download.php
  AdobeStockImageAdminUi/Controller/Adminhtml/Preview/RelatedImages.php
  AdobeStockImageAdminUi/Model/Listing/DataProvider.php
  dev/tests/unit/phpunit.xml
Labels: Priority: P2, Progress: acceptance testing, Severity: S2

#1785 [Refactoring] Improved exception handling
  AdobeStockClient/Model/ConnectionWrapper.php
  AdobeStockImageAdminUi/Controller/Adminhtml/License/GetList.php
Labels: Progress: acceptance testing
