Repository magento/adobe-stock-integration, pull requests merged in 2020-07, with the labels that each got.

#1541 Fix Escape doesn't close the "Couldn't log you in..." message. Instead the Adobe Stock window is closed
  AdobeStockImageAdminUi/view/adminhtml/web/js/signIn.js
Labels: Progress: ready for delivery

#1532 Add file length validation on media gallery uploader
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Progress: ready for delivery

#1550 IPTC Reader && Writer Implementation for jpeg format
  MediaGalleryMetadata/Model/AddIptcMetadata.php
  MediaGalleryMetadata/Model/AddMetadata.php
  MediaGalleryMetadata/Model/AddXmpMetadata.php
  MediaGalleryMetadata/Model/ExtractMetadata.php
  MediaGalleryMetadata/Model/File.php
  MediaGalleryMetadata/Model/File/AddMetadata.php
  MediaGalleryMetadata/Model/File/ExtractMetadata.php
  MediaGalleryMetadata/Model/GetIptcMetadata.php
  MediaGalleryMetadata/Model/GetXmpMetadata.php
  MediaGalleryMetadata/Model/Gif/FileReader.php
  MediaGalleryMetadata/Model/Gif/Segment/XmpReader.php
  MediaGalleryMetadata/Model/Jpeg/FileReader.php
  MediaGalleryMetadata/Model/Jpeg/FileWriter.php
  MediaGalleryMetadata/Model/Jpeg/Segment/IptcReader.php
  MediaGalleryMetadata/Model/Jpeg/Segment/IptcWriter.php
  MediaGalleryMetadata/Model/Jpeg/Segment/XmpReader.php
  MediaGalleryMetadata/Model/Jpeg/Segment/XmpWriter.php
  MediaGalleryMetadata/Model/Metadata.php
  MediaGalleryMetadata/Model/Png/FileReader.php
  MediaGalleryMetadata/Model/Png/FileWriter.php
  MediaGalleryMetadata/Model/Png/Segment/XmpReader.php
  MediaGalleryMetadata/Model/Png/Segment/XmpWriter.php
  MediaGalleryMetadata/Model/Segment.php
  MediaGalleryMetadata/Model/SegmentNames.php
  MediaGalleryMetadata/Model/XmpTemplate.php
  MediaGalleryMetadata/composer.json
  MediaGalleryMetadata/etc/default.xmp
  MediaGalleryMetadata/etc/di.xml
  MediaGalleryMetadataApi/Api/AddMetadataInterface.php
  MediaGalleryMetadataApi/Api/Data/MetadataInterface.php
  MediaGalleryMetadataApi/Api/ExtractMetadataInterface.php
  MediaGalleryMetadataApi/Model/AddMetadataComposite.php
  MediaGalleryMetadataApi/Model/ExtractMetadataPool.php
  MediaGalleryMetadataApi/Model/FileInterface.php
  MediaGalleryMetadataApi/Model/FileReaderInterface.php
  MediaGalleryMetadataApi/Model/FileWriterInterface.php
  MediaGalleryMetadataApi/Model/MetadataReaderInterface.php
  MediaGalleryMetadataApi/Model/MetadataWriterInterface.php
  MediaGalleryMetadataApi/Model/SegmentInterface.php
Labels: Progress: acceptance testing

#1556 [MFTF] Cover User sees warning when deleting image if it's used on storefront
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryAssertWarningMessageActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryClickDeleteImagesButtonActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryConfirmDeleteImagesActionGroup.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryDeleteImagesInBulkTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageFileTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageWithWarningPopupTest.xml
Labels: MFTF coverage, Progress: acceptance testing

#1564 [MFTF] Add search filter to drop defaults filters and have unique images
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridSortTest.xml
Labels: Progress: acceptance testing

#1525 Introduce Category grid page
  MediaGalleryCatalogUi/Controller/Adminhtml/Category/Index.php
  MediaGalleryCatalogUi/LICENSE.txt
  MediaGalleryCatalogUi/LICENSE_AFL.txt
  MediaGalleryCatalogUi/Model/Listing/DataProvider.php
  MediaGalleryCatalogUi/README.md
  MediaGalleryCatalogUi/Test/Mftf/ActionGroup/AdminAssertCategoryGridPageDetailsActionGroup.xml
  MediaGalleryCatalogUi/Test/Mftf/ActionGroup/AdminOpenCategoryGridPageActionGroup.xml
  MediaGalleryCatalogUi/Test/Mftf/Page/AdminMediaGalleryCatalogUiCategoryGridPage.xml
  MediaGalleryCatalogUi/Test/Mftf/Section/AdminMediaGalleryCatalogUiCategoryGridSection.xml
  MediaGalleryCatalogUi/Test/Mftf/Test/AdminMediaGalleryCatalogUiVerifyCategoryGridPageTest.xml
  MediaGalleryCatalogUi/Ui/Component/Listing/Columns/Path.php
  MediaGalleryCatalogUi/Ui/Component/Listing/Columns/Thumbnail.php
  MediaGalleryCatalogUi/composer.json
  MediaGalleryCatalogUi/etc/adminhtml/routes.xml
  MediaGalleryCatalogUi/etc/module.xml
  MediaGalleryCatalogUi/modman
  MediaGalleryCatalogUi/registration.php
  MediaGalleryCatalogUi/view/adminhtml/layout/media_gallery_catalog_category_index.xml
  MediaGalleryCatalogUi/view/adminhtml/ui_component/media_gallery_category_listing.xml
  MediaGalleryCatalogUi/view/adminhtml/web/css/source/_module.less
  _metapackage/composer.json
  modman
Labels: MFTF coverage, Progress: ready for delivery

#1531 Introduce used in filter
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/EntityType.php
  MediaGalleryUi/Ui/Component/Listing/Filters/Options/UsedIn.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: ready for delivery

#1558 Depend "Delete Images" button visibility on images records count
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/js/grid/massaction/massactions.js
  MediaGalleryUi/view/adminhtml/web/template/grid/massactions/count.html
Labels: Progress: ready for delivery

#1510 #1496: Add hash to asset on uploading the image to magento
  MediaGallerySynchronization/Model/CreateAssetFromFile.php
  MediaGallerySynchronization/Model/GetContentHash.php
  MediaGallerySynchronization/Test/Integration/Model/GetContentHashInterfaceTest.php
  MediaGallerySynchronization/Test/Integration/_files/magento.jpg
  MediaGallerySynchronization/Test/Integration/_files/magento_2.jpg
  MediaGallerySynchronization/Test/Integration/_files/magento_3.png
  MediaGallerySynchronization/etc/di.xml
  MediaGallerySynchronizationApi/Model/GetContentHashInterface.php
Labels: Progress: ready for delivery

#1572 #1561: Grammar mistakes in "Delete image" confirmation message
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImageWithDetailConfirmation.js
Labels: Progress: ready for delivery

#1576 [2.0.0][MFTF] Add search filter to drop defaults filters and have unique images
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminAdobeStockGridSortTest.xml
  AdobeStockImageAdminUi/Test/Mftf/Test/AdminMediaGalleryViewAdobeStockDetailsTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryUploadCategoryImageTest.xml
Labels: 2.4.0-develop: :two:

#1508 #1494: Save image content hash to the media asset when saving image from the Adobe Stock
  AdobeStockImage/Model/Extract/MediaGalleryAsset.php
  AdobeStockImage/Model/SaveMediaGalleryAsset.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
  AdobeStockImage/composer.json
Labels: Progress: review

#1571 Adjust getIMageDetails to the bulk parameters
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
Labels: Progress: acceptance testing

#1579 #1573 :- Possible to Edit image and save it with empty name
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Award: bug fix, Progress: ready for delivery, Severity: S1

#1491 Dynamically create folder by current_tree_path when instance changed
  MediaGalleryUi/view/adminhtml/web/js/directory/directoryTree.js
Labels: Progress: ready for delivery

#1580 [MFTF] Cover Used In Media Gallery filter with MFTF
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryApplyUsedInFilterActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryFiltersSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryVerifyUsedInFilterTest.xml
Labels: MFTF coverage, Progress: changes requested

#1586 #1574: Name and Description fields, from Edit Image window, have not length or allowed symbols validation
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Progress: ready for delivery

#1590 #1582 & #1583 Improvements
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyImageFilenameActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryViewDetailsSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminStandaloneMediaGalleryViewDetailsTest.xml
  MediaGalleryUi/view/adminhtml/web/template/image/image-details.html
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Progress: ready for delivery

#1591 The newly added Description will appear in Image Details only after the web page is refreshed
  MediaGalleryUi/view/adminhtml/web/js/image/image-actions.js
  MediaGalleryUi/view/adminhtml/web/js/image/image-details.js
Labels: Progress: ready for delivery

#1595 Introduce Duplicated images filter
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Duplicated.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryApplyDuplicatedFilterActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryFiltersSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryDuplicatedImagesTest.xml
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/web/template/grid/filter/checkbox.html
Labels: MFTF coverage, Progress: ready for delivery

#1597 #1589: Hitting Enter key on Edit Image page redirects the user to Magento Dashboard instead of Saving the image
  MediaGalleryUi/view/adminhtml/web/js/image/image-edit.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Progress: ready for delivery

#1593 Used In Content Entities Filters
  MediaGalleryCatalogUi/Test/Mftf/Test/AdminMediaGalleryCatalogUiUsedInCategoryFilterTest.xml
  MediaGalleryCatalogUi/Test/Mftf/Test/AdminMediaGalleryCatalogUiUsedInProductFilterTest.xml
  MediaGalleryCatalogUi/etc/adminhtml/di.xml
  MediaGalleryCatalogUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryCatalogUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryCmsUi/Controller/Adminhtml/Block/Search.php
  MediaGalleryCmsUi/Controller/Adminhtml/Page/Search.php
  MediaGalleryCmsUi/LICENSE.txt
  MediaGalleryCmsUi/LICENSE_AFL.txt
  MediaGalleryCmsUi/README.md
  MediaGalleryCmsUi/Test/Mftf/Test/AdminMediaGalleryCmsUiUsedInBlocksFilterTest.xml
  MediaGalleryCmsUi/Test/Mftf/Test/AdminMediaGalleryCmsUiUsedInPagesFilterTest.xml
  MediaGalleryCmsUi/composer.json
  MediaGalleryCmsUi/etc/adminhtml/di.xml
  MediaGalleryCmsUi/etc/adminhtml/routes.xml
  MediaGalleryCmsUi/etc/module.xml
  MediaGalleryCmsUi/modman
  MediaGalleryCmsUi/registration.php
  MediaGalleryCmsUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryCmsUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/Entity.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AssertAdminEnhancedMediaGalleryImageDeletedActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryFiltersSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageContextMenuTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageFileTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsDeleteImageTest.xml
  _metapackage/composer.json
  modman
Labels: Progress: ready for delivery

#1622 #1562: A line appears on tabs [UI]
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: ready for delivery

#1623 #1604: The "See more" is not in correct position on device mode
  AdobeStockImageAdminUi/view/adminhtml/web/css/source/_module.less
Labels: Progress: ready for delivery

#1602 Added Content Status and Store View filters
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/ContentField.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryApplySelectFilterActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminOpenMediaGalleryFromPageNoEditorActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryFiltersSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDisabledContentFilterTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryEnabledContentFilterTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryStoreViewCategoryFilterTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryStoreViewContentFilterTest.xml
  MediaGalleryUi/Ui/Component/Listing/Filters/Options/Status.php
  MediaGalleryUi/Ui/Component/Listing/Filters/Options/Store.php
  MediaGalleryUi/etc/adminhtml/di.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  modman
Labels: Priority: P2, Progress: ready for delivery

#1601 Add "Not used anywhere" option to the Used In filter
  MediaGalleryUi/Model/SearchCriteria/CollectionProcessor/FilterProcessor/EntityType.php
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryVerifyNotUsedOptionFilterTest.xml
  MediaGalleryUi/etc/adminhtml/di.xml
Labels: MFTF coverage, Progress: ready for delivery

#1624 #1620: Not possible to enter multi-line image Description
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Progress: ready for delivery

#1628 #1619: Change the position of "Show duplicates" checkbox
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1596 Polpulate asset metadata on uploading the image to magento && Populate media asset description when saving image from adobe stock
  AdobeStockImage/Model/Extract/MediaGalleryAsset.php
  AdobeStockImage/Model/SaveMediaGalleryAsset.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
  AdobeStockImage/composer.json
  MediaGalleryCmsUi/Test/Mftf/Test/AdminMediaGalleryCmsUiUsedInPagesFilterTest.xml
  MediaGalleryIntegration/Plugin/SaveBaseCategoryImageInformation.php
  MediaGalleryIntegration/Plugin/SaveImageInformation.php
  MediaGalleryIntegration/composer.json
  MediaGalleryMetadata/etc/di.xml
  MediaGallerySynchronization/Model/CreateAssetFromFile.php
  MediaGallerySynchronization/Model/FetchMediaStorageFileBatches.php
  MediaGallerySynchronization/Model/ImportImageFileKeywords.php
  MediaGallerySynchronization/Model/ImportMediaAsset.php
  MediaGallerySynchronization/Model/SynchronizeFiles.php
  MediaGallerySynchronization/composer.json
  MediaGallerySynchronization/etc/di.xml
  MediaGallerySynchronizationApi/Api/ImportFileInterface.php
  MediaGallerySynchronizationApi/Model/ImportFileComposite.php
  MediaGalleryUi/Model/UploadImage.php
  MediaGalleryUi/Plugin/ResizeSyncedFiles.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyImageKeywordsActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryVerifyImageTitleActionGroup.xml
  MediaGalleryUi/Test/Mftf/Data/AdminEnhancedMediaGalleryImageData.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryViewDetailsSection.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryUploadImageWithMetadataTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryVerifyAssetFilterTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryDeleteImageWithWarningPopupTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryEditImageDetailsTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryUploadCategoryImageTest.xml
  MediaGalleryUi/Test/Mftf/Test/AdminMediaGalleryViewDetailsDeleteImageTest.xml
  MediaGalleryUi/Test/Unit/Model/UploadImageTest.php
  MediaGalleryUi/composer.json
  MediaGalleryUi/etc/di.xml
Labels: MFTF coverage, Progress: ready for delivery

#1608 #1599: Underscore symbol is not allowed in Image name and Description. (Edit window)
  MediaGalleryUi/view/adminhtml/templates/image_edit_details.phtml
  MediaGalleryUi/view/adminhtml/templates/image_edit_details_standalone.phtml
  MediaGalleryUi/view/adminhtml/web/js/validation/validate-image-description.js
  MediaGalleryUi/view/adminhtml/web/js/validation/validate-image-title.js
  MediaGalleryUi/view/adminhtml/web/template/image/image-edit.html
Labels: Progress: ready for delivery

#1643 1543: Uncaught JS Error after authorization failure on licensing image from media gallery
  AdobeStockImageAdminUi/view/adminhtml/web/js/mediaGallery/grid/columns/image/licenseActions.js
Labels: Progress: ready for delivery

#1607 #1444: Save metadata to file on editing
  MediaGalleryMetadata/etc/di.xml
  MediaGalleryUi/Controller/Adminhtml/Image/SaveDetails.php
  MediaGalleryUi/Model/UpdateAsset.php
  MediaGalleryUi/Model/UpdateAsset/SaveMetadataToFile.php
  MediaGalleryUi/Model/UpdateAsset/UpdateKeywords.php
  MediaGalleryUi/composer.json
Labels: Progress: ready for delivery

#1625 #1609: [Refactoring] DateTime handling and formatting
  MediaGallerySynchronization/Model/SynchronizeFiles.php
  MediaGalleryUi/Model/AssetDetailsProvider/CreatedAt.php
  MediaGalleryUi/Model/AssetDetailsProvider/UpdatedAt.php
Labels: Progress: ready for delivery

#1651 Skip flaky tests
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryDeleteImagesInBulkTest.xml
Labels: Progress: review

#1656 Typo fix on Uploading long image name. Changed "chracters" to "characters"
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Frontend/UI, Progress: acceptance testing, Severity: S4

#1644 #1630: [Refactoring] Backend type check during uploading an image
  MediaGalleryUi/Controller/Adminhtml/Image/Upload.php
  MediaGalleryUi/Model/UploadImage.php
  MediaGalleryUi/Test/Unit/Model/UploadImageTest.php
Labels: Progress: ready for delivery

#1659 Handling jpeg image that is corrupted at the end
  MediaGalleryMetadata/Model/Jpeg/FileReader.php
Labels: Progress: review

#1668 Fix iptc file segment replacement
  MediaGalleryMetadata/Model/AddIptcMetadata.php
Labels: Progress: ready for delivery

#1660 #1633: [Refactoring] Misc
  AdobeStockImageAdminUi/view/adminhtml/ui_component/media_gallery_listing.xml
  AdobeStockImageAdminUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryCatalogUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryCatalogUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryCmsUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryCmsUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1648 1626: Modified date and time changes to original after Media Gallery synchronization
  MediaGallerySynchronization/Model/CreateAssetFromFile.php
  MediaGallerySynchronization/Model/SynchronizeFiles.php
Labels: Progress: ready for delivery

#1672 #1657: The position of the filters is changed when Directory filter is applied
  MediaGalleryUi/view/adminhtml/ui_component/media_gallery_listing.xml
  MediaGalleryUi/view/adminhtml/ui_component/standalone_media_gallery_listing.xml
Labels: Progress: ready for delivery

#1662 Remove duplicated selector
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminMediaGalleryApplyUsedInFilterActionGroup.xml
  MediaGalleryUi/Test/Mftf/Section/AdminEnhancedMediaGalleryFiltersSection.xml
Labels: Progress: ready for delivery

#1658 Fix delete images in bulk test && small improvements
  MediaGalleryIntegration/Model/OpenDialogUrlProvider.php
  MediaGalleryIntegration/Plugin/SaveBaseCategoryImageInformation.php
  MediaGalleryIntegration/Plugin/SaveImageInformation.php
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryAssertMassActionModeDetailsActionGroup.xml
  MediaGalleryUi/Test/Mftf/ActionGroup/AdminEnhancedMediaGalleryAssertMassActionModeNotActiveActionGroup.xml
  MediaGalleryUi/Test/Mftf/Test/AdminEnhancedMediaGalleryDeleteImagesInBulkTest.xml
  MediaGalleryUi/view/adminhtml/web/js/action/deleteImages.js
  MediaGalleryUi/view/adminhtml/web/js/image-uploader.js
Labels: Priority: P1, Priority: P3, Progress: review, Severity: S2, Severity: S3

#1679 1676: Remove Travis CI related files from the project
  .coveralls.yml
  .travis.yml
  README.md
  dev/travis/after_failure.sh
  dev/travis/after_script.sh
  dev/travis/before_install.sh
  dev/travis/before_script.sh
  dev/travis/config/apache_virtual_host
  dev/travis/script.sh
Labels: Progress: acceptance testing

#1632 [Refactoring] MediaGalleryMetadata Modules
  AdobeStockImage/Model/SaveMediaGalleryAsset.php
  AdobeStockImage/Test/Unit/Model/SaveMediaGalleryAssetTest.php
  MediaGalleryMetadata/Model/AddIptcMetadata.php
  MediaGalleryMetadata/Model/AddMetadata.php
  MediaGalleryMetadata/Model/AddXmpMetadata.php
  MediaGalleryMetadata/Model/ExtractMetadata.php
  MediaGalleryMetadata/Model/File/AddMetadata.php
  MediaGalleryMetadata/Model/File/ExtractMetadata.php
  MediaGalleryMetadata/Model/Gif/ReadFile.php
  MediaGalleryMetadata/Model/Gif/Segment/ReadXmp.php
  MediaGalleryMetadata/Model/Gif/Segment/WriteXmp.php
  MediaGalleryMetadata/Model/Gif/WriteFile.php
  MediaGalleryMetadata/Model/Jpeg/ReadFile.php
  MediaGalleryMetadata/Model/Jpeg/Segment/ReadIptc.php
  MediaGalleryMetadata/Model/Jpeg/Segment/ReadXmp.php
  MediaGalleryMetadata/Model/Jpeg/Segment/WriteIptc.php
  MediaGalleryMetadata/Model/Jpeg/Segment/WriteXmp.php
  MediaGalleryMetadata/Model/Jpeg/WriteFile.php
  MediaGalleryMetadata/Model/Metadata.php
  MediaGalleryMetadata/Model/Png/ReadFile.php
  MediaGalleryMetadata/Model/Png/Segment/ReadXmp.php
  MediaGalleryMetadata/Model/Png/Segment/WriteXmp.php
  MediaGalleryMetadata/Model/Png/WriteFile.php
  MediaGalleryMetadata/Test/Integration/Model/AddMetadataTest.php
  MediaGalleryMetadata/Test/Integration/Model/ExtractMetadataTest.php
  MediaGalleryMetadata/Test/Integration/Model/Gif/Segment/XmpTest.php
  MediaGalleryMetadata/Test/Integration/Model/Jpeg/Segment/IptcTest.php
  MediaGalleryMetadata/Test/Integration/Model/Jpeg/Segment/XmpTest.php
  MediaGalleryMetadata/etc/di.xml
  MediaGalleryMetadataApi/Api/Data/MetadataInterface.php
  MediaGalleryMetadataApi/Model/AddMetadataComposite.php
  MediaGalleryMetadataApi/Model/ExtractMetadataComposite.php
  MediaGalleryMetadataApi/Model/ExtractMetadataPool.php
  MediaGalleryMetadataApi/Model/ReadFileInterface.php
  MediaGalleryMetadataApi/Model/ReadMetadataInterface.php
  MediaGalleryMetadataApi/Model/WriteFileInterface.php
  MediaGalleryMetadataApi/Model/WriteMetadataInterface.php
  MediaGallerySynchronization/Model/CreateAssetFromFile.php
  MediaGallerySynchronization/Model/FetchMediaStorageFileBatches.php
  MediaGallerySynchronization/Model/ImportImageFileKeywords.php
  MediaGallerySynchronization/etc/di.xml
Labels: Priority: P1, Progress: changes requested, Severity: S2
